// src/app/components/monsters/monster-lore/monster-lore.component.ts
﻿import { Component, OnDestroy, OnInit } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { combineLatest, Subscription } from 'rxjs';
import { DomSanitizer } from '@angular/platform-browser';

import { DataService } from '../../../services/data.service';
declare const utils: any // Javascript utilities

@Component({
    selector: 'monster-lore',
    styleUrls: ['./monster-lore.component.css'],
    templateUrl: './monster-lore.component.html',
    standalone: false
})
export class MonsterLoreComponent implements OnInit, OnDestroy {
    monsters: any[] = [];
    monsterSubtypes: any[] = [];
    subscriptions: Subscription[] = [];
    shownCard = '';
    shownSubtype = '';

    constructor(private route: ActivatedRoute, private router: Router, public domSanitizer: DomSanitizer, public dataService: DataService) { }

    ngOnInit(): void {
        window.history.forward();
        this.subscriptions.push(combineLatest([
            this.dataService.getMonsters(),
            this.dataService.getMonsterSubtypes()
        ]).subscribe((data: any) => {
            this.monsters = data[0];
            this.monsterSubtypes = data[1];
            const index = this.route.snapshot.queryParamMap.get('index');
            if (index) {
                const monsterSubtype = this.monsterSubtypes.find((monsterSubtype) => monsterSubtype.index === index);
                if (monsterSubtype) {
                    this.showSubtype(index);
                    utils.scrollIntoView(monsterSubtype.index);
                }
            }
        }));
    }

    ngOnDestroy(): void {
        // Unsubscribe all subscriptions to avoid memory leak
        this.subscriptions.forEach(subscription => subscription.unsubscribe());
    }

    expandCard(index: string, expanded: boolean) {
        if (expanded) {
            this.shownCard = index;
            utils.scrollIntoView(index);
        }
    }

    showSubtype(index: string) {
        console.log(index);
        if (this.shownSubtype == index) {
            this.shownSubtype = '';
        } else {
            this.shownSubtype = index;
            utils.scrollIntoView(index);
        }
        this.router.navigate([], {
            queryParams: { index: index },
            queryParamsHandling: 'merge',
        });
    }

}

﻿@for (subtype of monsterSubtypes; track subtype) {
  <div class="list">
    <div class="card outer w-100" [class.active]="shownSubtype == subtype.index" [id]="subtype.index">
      <div class="card-header clickable" (click)="showSubtype(subtype.index)">
        <div class="card-title">{{subtype.name}}</div>
      </div>
      @if (shownSubtype == subtype.index) {
        <div class="card-body">
          <div [innerHtml]="domSanitizer.bypassSecurityTrustHtml(subtype.desc)"></div>
          <br/>
          <h5>Monsters</h5>
          @for (monster of monsters; track monster) {
            <div class="inner-list" [id]="monster.index">
              @if (subtype.monsters.includes(monster.index)) {
                <app-monster [monster]="monster" [expand]="shownCard==monster.index" (expanded)="expandCard(monster.index, $event)" [cardType]="'inner'"></app-monster>
              }
            </div>
          }
          <div class="card-footer">
            {{subtype.book}} (page {{subtype.page}})
          </div>
        </div>
      }
    </div>
  </div>
}

// src/components/monsters/MonsterLore.jsx
import { useState, useEffect } from 'react';
import { useSearchParams } from 'react-router-dom';
import { useMonsters, useMonsterSubtypes } from '../../data/dataService';
import Monster from './Monster';
import './MonsterLore.css';

// Javascript utilities (matching Angular)
const utils = {
    scrollIntoView: function(index) {
        const element = document.getElementById(index);
        if (element) {
            element.scrollIntoView({ behavior: 'smooth', block: 'center' });
        }
    }
};

function MonsterLore() {
    const [monsters, setMonsters] = useState([]);
    const [monsterSubtypes, setMonsterSubtypes] = useState([]);
    const [shownCard, setShownCard] = useState('');
    const [shownSubtype, setShownSubtype] = useState('');
    const [searchParams, setSearchParams] = useSearchParams();

    // Fetch data
    const { data: monstersData, loading: monstersLoading } = useMonsters();
    const { data: monsterSubtypesData, loading: subtypeLoading } = useMonsterSubtypes();

    useEffect(() => {
        if (monstersData && monstersData.length > 0) {
            setMonsters(monstersData);

            // Check for index parameter in URL
            const index = searchParams.get('index');
            if (index) {
                const monsterSubtype = monsterSubtypesData.find(subtype => subtype.index === index);
                if (monsterSubtype) {
                    showSubtype(index, false);
                    utils.scrollIntoView(index);
                }
            } else {
                // Set search filters from localStorage - default to "All" when no saved data
                const savedFilter = localStorage.getItem('monsterLoreFilter');
                if (!savedFilter) {
                    const defaultFilter = { category: 'All' };
                    localStorage.setItem('monsterLoreFilter', JSON.stringify(defaultFilter));
                }
            }
        }

        if (monsterSubtypesData) {
            setMonsterSubtypes(monsterSubtypesData);
        }
    }, [monstersData, monsterSubtypesData]);

    const expandCard = (index, expanded) => {
        if (expanded) {
            setShownCard(index);
            utils.scrollIntoView(index);
        } else {
            setShownCard('');
        }
    };

    const showSubtype = (index, updateUrl = true) => {
        console.log(index);
        if (shownSubtype === index) {
            setShownSubtype('');
            if (updateUrl) {
                setSearchParams({});
            }
        } else {
            setShownSubtype(index);
            utils.scrollIntoView(index);
            if (updateUrl) {
                setSearchParams({ index });
            }
        }
    };

    if (monstersLoading || subtypeLoading) {
        return <div className="list"><div>Loading monster lore...</div></div>;
    }

    return (
        <>
            {monsterSubtypes.map((subtype) => (
                <div className="list" key={subtype.index}>
                    <div 
                        className={`card outer w-100 ${shownSubtype === subtype.index ? 'active' : ''}`} 
                        id={subtype.index}
                    >
                        <div className="card-header clickable" onClick={() => showSubtype(subtype.index)}>
                            <div className="card-title">{subtype.name}</div>
                        </div>
                        {shownSubtype === subtype.index && (
                            <div className="card-body">
                                <div dangerouslySetInnerHTML={{ __html: subtype.desc }} />
                                <br/>
                                <h5>Monsters</h5>
                                {monsters.map((monster) => (
                                    <div className="inner-list" key={monster.index} id={monster.index}>
                                        {subtype.monsters.includes(monster.index) && (
                                            <Monster 
                                                monster={monster}
                                                expand={shownCard === monster.index}
                                                onExpand={(expanded) => expandCard(monster.index, expanded)}
                                                cardType="inner"
                                            />
                                        )}
                                    </div>
                                ))}
                                <div className="card-footer">
                                    {subtype.book} (page {subtype.page})
                                </div>
                            </div>
                        )}
                    </div>
                </div>
            ))}
        </>
    );
}

export default MonsterLore;
