// src/app/components/spell/spell.component.ts
﻿import { Component, EventEmitter, Input, Output } from '@angular/core';

@Component({
  selector: 'app-spell',
  styleUrls: ['./spell.component.scss'],
  templateUrl: './spell.component.html'
})
export class SpellComponent {

  @Input() spell: any = null;
  @Output() readonly knownChanged = new EventEmitter<boolean>(); // Bubble up that the spell is known
  @Output() readonly preparedChanged = new EventEmitter<boolean>(); // Bubble up that the spell is prepared

  getClasses() {
    let classes = '';
    this.spell.classes.forEach((spellClass: any) => {
      classes += `${spellClass.name}, `;
    });
    return classes.substr(0, classes.length-2);
  }

  getLevelText(level: number) {
    switch (level) {
      case 0:
        return 'Cantrip';
      case 1:
        return '1st-level';
      case 2:
        return '2nd-level';
      case 3:
        return '3rd-level';
      default:
        return level + 'th-level';
    }
  }

  toggleDetails(spell: any) {
    if (spell.ui) {
      spell.ui.show = !spell.ui.show;
    } else {
      spell.ui = {};
      spell.ui.show = true;
    }
  }

  toggleKnown(spell: any) {
    spell.known = !spell.known;
    // A spell must be known to be prepared
    if(spell.known == false && spell.prepared == true) {
      spell.prepared = false;
      this.preparedChanged.emit(spell.prepared);
    }
    this.knownChanged.emit(spell.known);
  }

  togglePrepared(spell: any) {
    spell.prepared = !spell.prepared;
    this.preparedChanged.emit(spell.prepared);
  }

}

﻿@if (spell != null) {
  <div class="card w-100" [class.active]="expand">
    <div class="card-header clickable">
      <div (click)="toggleDetails()">
        <div class="card-title">{{spell.name}}</div>
        <i>{{getLevelText(spell.level)}}&nbsp;{{spell.school.toLowerCase()}}&nbsp;@if (spell.ritual) {
          <span>(ritual)</span>
        }</i><br />
      </div>
      <div>
        <div class="form-check">
          <input class="form-check-input" type="checkbox" id="prepared" name="prepared" [disabled]="spell.known != true" [(ngModel)]="spell.prepared" #preparedControl="ngModel" (click)="togglePrepared(spell)">
          <label class="form-check-label" for="prepared">
            Prepared
          </label>
        </div>
        <div class="form-check">
          <input class="form-check-input" type="checkbox" id="known" name="known" [(ngModel)]="spell.known" #knownControl="ngModel" (click)="toggleKnown(spell)">
          <label class="form-check-label" for="known">
            Known
          </label>
        </div>
      </div>
    </div>
    @if (expand) {
      <div class="card-body">
        <div class="card-text">
          <div class="stats">
            <div>
              <b>Casting Time:</b>&nbsp;{{spell.casting_time}}<br />
              <b>Range:</b>&nbsp;{{spell.range}}<br />
              <b>Components:</b>&nbsp;{{spell.components}}&nbsp;@if (spell.material) {
              <span
              >({{spell.material}})</span>
              }<br />
              <b>Duration:</b>&nbsp;@if (spell.concentration) {
              <span>Concentration,&nbsp;</span>
              }{{spell.duration}}<br />
            </div>
            <div>
              <b>Classes:</b>&nbsp;{{getClasses()}}<br />
              @if (spell.area_of_effect) {
                <div>
                  <b>Area of Effect:</b>&nbsp;{{spell.area_of_effect.size}} foot {{spell.area_of_effect.type}}<br />
                </div>
              }
              @if (spell.damage) {
                <div>
                  <b>Damage Type:</b>&nbsp;{{spell.damage.damage_type}}<br />
                </div>
              }
              @if (spell.dc) {
                <div>
                  <b>DC:</b>&nbsp;{{spell.dc.dc_type}} ({{spell.dc.dc_success}})<br />
                </div>
              }
            </div>
          </div>
          <hr>
            @for (desc of spell.desc; track desc) {
              <div>
                <span [innerHtml]="domSanitizer.bypassSecurityTrustHtml(desc)"></span>
              </div>
            }
            @if (spell.higher_level != null) {
              <div>
                <br/><b>At higher levels.</b>&nbsp;{{spell.higher_level}}<br />
              </div>
            }
          </div>
        </div>
      }
    </div>
  }

// src/components/spells/Spell.jsx
import { useState, useEffect } from 'react';

function Spell({ spell, expand, onExpand, onKnownChange, onPreparedChange }) {
    const [isExpanded, setIsExpanded] = useState(expand);

    // Update local state when prop changes
    useEffect(() => {
        if (expand !== isExpanded) {
            setIsExpanded(expand);
        }
    }, [expand]);

    const getClasses = () => {
        if (!spell.classes || spell.classes.length === 0) {
            return '';
        }
        let classes = '';
        spell.classes.forEach((spellClass) => {
            classes += `${spellClass}, `;
        });
        return classes.substring(0, classes.length - 2);
    };

    const getLevelText = (level) => {
        switch (level) {
            case 0:
                return 'Cantrip';
            case 1:
                return '1st-level';
            case 2:
                return '2nd-level';
            case 3:
                return '3rd-level';
            default:
                return level + 'th-level';
        }
    };

    const toggleDetails = () => {
        setIsExpanded(!isExpanded);
        onExpand(!isExpanded);
    };

    const toggleKnown = () => {
        spell.known = !spell.known;
        
        // A spell must be known to be prepared
        if (spell.known === false && spell.prepared === true) {
            spell.prepared = false;
            onPreparedChange(spell.index, false);
        }
        
        onKnownChange(spell.index, spell.known);
    };

    const togglePrepared = () => {
        spell.prepared = !spell.prepared;
        onPreparedChange(spell.index, spell.prepared);
    };

    if (!spell) {
        return null;
    }

    // Handle HTML sanitization (simplified - in production use DOMPurify or similar)
    const sanitizeHtml = (htmlString) => {
        if (!htmlString) return '';
        // Simple approach: just return the string
        // In production, use DOMPurify: https://www.npmjs.com/package/dompurify
        return htmlString;
    };

    const renderDescription = () => {
        if (!spell.desc || spell.desc.length === 0) {
            return null;
        }

        return spell.desc.map((desc, index) => (
            <div key={index}>
                <span dangerouslySetInnerHTML={{ __html: sanitizeHtml(desc) }} />
            </div>
        ));
    };

    return (
        <div className={`card w-100 ${isExpanded ? 'active' : ''}`} id={spell.index}>
            <div className="card-header clickable">
                <div onClick={toggleDetails}>
                    <div className="card-title">{spell.name}</div>
                    <i>{getLevelText(spell.level)}&nbsp;{spell.school.toLowerCase()}</i>
                    {spell.ritual && (
                        <span> (ritual)</span>
                    )}<br />
                </div>
                <div>
                    <div className="form-check">
                        <input 
                            className="form-check-input" 
                            type="checkbox" 
                            id="prepared" 
                            name="prepared"
                            disabled={spell.known !== true}
                            checked={spell.prepared || false}
                            onChange={togglePrepared}
                        />
                        <label className="form-check-label" htmlFor="prepared">
                            Prepared
                        </label>
                    </div>
                    <div className="form-check">
                        <input 
                            className="form-check-input" 
                            type="checkbox" 
                            id="known" 
                            name="known"
                            checked={spell.known || false}
                            onChange={toggleKnown}
                        />
                        <label className="form-check-label" htmlFor="known">
                            Known
                        </label>
                    </div>
                </div>
            </div>

            {isExpanded && (
                <div className="card-body">
                    <div className="card-text">
                        <div className="stats">
                            <div>
                                <b>Casting Time:</b>&nbsp;{spell.casting_time}<br />
                                <b>Range:</b>&nbsp;{spell.range}<br />
                                <b>Components:</b>&nbsp;{spell.components}
                                {spell.material && (
                                    <span>({spell.material})</span>
                                )}<br />
                                <b>Duration:</b>&nbsp;{spell.concentration && (
                                    <span>Concentration,&nbsp;</span>
                                )}{spell.duration}<br />
                            </div>
                            <div>
                                <b>Classes:</b>&nbsp;{getClasses()}<br />
                                {spell.area_of_effect && (
                                    <div>
                                        <b>Area of Effect:</b>&nbsp;{spell.area_of_effect.size} foot {spell.area_of_effect.type}<br />
                                    </div>
                                )}
                                {spell.damage && (
                                    <div>
                                        <b>Damage Type:</b>&nbsp;{spell.damage.damage_type}<br />
                                    </div>
                                )}
                                {spell.dc && (
                                    <div>
                                        <b>DC:</b>&nbsp;{spell.dc.dc_type} ({spell.dc.dc_success})<br />
                                    </div>
                                )}
                            </div>
                        </div>

                        <hr />

                        {renderDescription()}

                        {spell.higher_level && (
                            <div>
                                <br /><b>At higher levels.</b>&nbsp;{spell.higher_level}<br />
                            </div>
                        )}
                    </div>
                </div>
            )}
        </div>
    );
}

export default Spell;
