// src/components/rules/AbilityScore.jsx
import { renderHtmlContent } from '../../utils/htmlUtils';

function AbilityScore({ abilityScore, expand, onExpand }) {
    const isExpanded = expand;

    const getSkills = () => {
        if (!abilityScore.skills || abilityScore.skills.length === 0) {
            return '';
        }
        const skills = abilityScore.skills.join(', ');
        return skills;
    };

    const toggleDetails = () => {
        onExpand(!isExpanded);
    };

    if (!abilityScore) {
        return null;
    }

    const skills = getSkills();

    return (
        <div className={`card w-100 ${isExpanded ? 'active' : ''}`}>
            <div className="card-header clickable" onClick={toggleDetails}>
                <div>
                    <span className="card-title">
                        {abilityScore.full_name}
                    </span>
                    <div className="skills-column">
                        {skills && (
                            <span>
                                &nbsp;- {skills}
                            </span>
                        )}
                    </div>
                </div>
            </div>
            {isExpanded && (
                <div className="card-body">
                    <div 
                                            className="card-text"
                                            dangerouslySetInnerHTML={renderHtmlContent(abilityScore.description)}
                                         />
                </div>
            )}
        </div>
    );
}

export default AbilityScore;

// src/app/components/ability-score/ability-score.component.ts
﻿import { Component, Input } from '@angular/core';

@Component({
  selector: 'ability-score',
  styleUrls: ['./ability-score.component.scss'],
  templateUrl: './ability-score.component.html'
})
export class AbilityScoreComponent {

  @Input() abilityScore: any = null;

  getSkills() {
    let skills = '';
    this.abilityScore.skills.forEach((skill: any) => {
      skills += `${skill.name}, `;
    });
    return skills.substr(0, skills.length-2);
  }

  toggleDetails(abilityScore: any) {
    if (abilityScore.ui) {
      abilityScore.ui.show = !abilityScore.ui.show;
    } else {
      abilityScore.ui = {};
      abilityScore.ui.show = true;
    }
  }

}

﻿<div *ngIf="abilityScore != null" class="card w-100">
	<div class="card-header" (click)="toggleDetails(abilityScore)">
		<div class="card-title">{{abilityScore.full_name}}</div>
	</div>
	<div *ngIf="abilityScore.ui && abilityScore.ui.show" class="card-body">
		<b>Skills:</b>&nbsp;{{getSkills()}}<br />		
		<hr>
		<div class="card-text">
			<div class="removeExtraLine">
				<span *ngFor="let desc of abilityScore.desc">
					{{desc}}<br /><br />
				</span>
			</div>
		</div>
	</div>
</div>
