// src/app/components/rules/general-rule/general-rule.component.ts
﻿import { Component, Input, Output, EventEmitter, OnChanges } from '@angular/core';
import { DomSanitizer } from '@angular/platform-browser';
declare const utils: any // Javascript utilities

@Component({
    selector: 'general-rule',
    styleUrls: ['./general-rule.component.css'],
    templateUrl: './general-rule.component.html',
    standalone: false
})
export class GeneralRuleComponent implements OnChanges {

  @Input() expand = false;
  @Input() rule: any = null;
  @Output() expanded = new EventEmitter<boolean>();

  shownSubsection: string = '';

  constructor(public domSanitizer: DomSanitizer) {}

  ngOnChanges() {
    //console.log(this.rule);
  }

  showSubsection(subsection: string) {
    if(this.shownSubsection == subsection) {
      this.shownSubsection = '';
    } else {
      this.shownSubsection = subsection;
      utils.scrollIntoView(subsection);
    }
  }

  toggleDetails() {
    this.expand = !this.expand;
    this.expanded.emit(this.expand);
  }

}

﻿<div class="component">
	<div *ngIf="rule != null" class="card outer w-100" [class.active]="expand">
		<div class="card-header clickable" (click)="toggleDetails()">
			<div class="card-title">{{rule.name}}</div>
		</div>
		<div *ngIf="expand" class="card-body">
			<div *ngFor="let subsection of rule.subsections" [id]="subsection.index">
				<div class="card inner w-100" [class.active]="shownSubsection==subsection.index">
					<div class="inner card-header clickable" (click)="showSubsection(subsection.index)">
						<div class="card-title">{{subsection.name}}</div>
					</div>
					<div class="inner card-body hidden" [class.hidden]="shownSubsection!=subsection.index">
						<div [innerHtml]="domSanitizer.bypassSecurityTrustHtml(subsection.desc)"></div>
						<div *ngIf="subsection.page">{{subsection.book}} (page {{subsection.page}})</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

// src/components/rules/general-rule/GeneralRule.jsx
import { useState } from 'react';
import './GeneralRule.css';

// Javascript utilities (matching Angular)
const utils = {
    scrollIntoView: function(index) {
        const element = document.getElementById(index);
        if (element) {
            element.scrollIntoView({ behavior: 'smooth', block: 'center' });
        }
    }
};

function GeneralRule({ rule, expand = false, onExpand }) {
    const [shownSubsection, setShownSubsection] = useState('');

    const showSubsection = (subsection) => {
        if (shownSubsection === subsection) {
            setShownSubsection('');
        } else {
            setShownSubsection(subsection);
            utils.scrollIntoView(subsection);
        }
    };

    const toggleDetails = () => {
        const newExpandState = !expand;
        if (onExpand) {
            onExpand(newExpandState);
        }
    };

    if (!rule) {
        return null;
    }

    // Convert subsections to JSX with innerHtml handling
    const renderSubsections = () => {
        if (!rule.subsections) return null;

        return rule.subsections.map((subsection) => (
            <div key={subsection.index} id={subsection.index}>
                <div className={`inner card ${shownSubsection === subsection.index ? 'active' : ''}`}>
                    <div className="inner card-header clickable" onClick={() => showSubsection(subsection.index)}>
                        <div className="card-title">{subsection.name}</div>
                    </div>
                    <div className={`inner card-body ${shownSubsection !== subsection.index ? 'hidden' : ''}`}>
                        <div dangerouslySetInnerHTML={{ __html: subsection.desc }}></div>
                        {subsection.page && (
                            <div>{subsection.book} (page {subsection.page})</div>
                        )}
                    </div>
                </div>
            </div>
        ));
    };

    return (
        <div className="component">
            <div className={`card outer w-100 ${expand ? 'active' : ''}`}>
                <div className="card-header clickable" onClick={toggleDetails}>
                    <div className="card-title">{rule.name}</div>
                </div>
                {expand && (
                    <div className="card-body">
                        {renderSubsections()}
                    </div>
                )}
            </div>
        </div>
    );
}

export default GeneralRule;
