// src/components/names/Names.jsx
import { useState, useEffect } from 'react';
import { useNames } from '../../data/dataService';
import './Names.css';
import NameFilterForm from './NameFilterForm';
import NameListTable from './NameListTable';

function Names() {
    const [names, setNames] = useState([]);
    const [namesUsed, setNamesUsed] = useState([]);
    const [shownNames, setShownNames] = useState({
        familyType: null,
        firstNames: [],
        lastNames: []
    });
    const [filter, setFilter] = useState({
        index: '',
        type: 'Select', // race or building
        sex: 'Select',
        used: 'All'
    });

    // Fetch data
    const { data: namesData, loading } = useNames();

    useEffect(() => {
        if (namesData && namesData.length > 0) {
            setNames(namesData);

            // Set search filters from localStorage
            let filterJson = localStorage.getItem('namesFilter');
            if (filterJson) {
                const savedFilter = JSON.parse(filterJson);
                
                // Set used names from localStorage first
                let namesUsedJson = localStorage.getItem('namesUsed');
                if (namesUsedJson != null) {
                    setNamesUsed(JSON.parse(namesUsedJson));
                }

                // Set the filter and then call getNames if we have valid selections
                setFilter({ ...filter, ...savedFilter });
                
                // If we have valid selections from localStorage, call getNames after filter is set
                if (savedFilter.index && savedFilter.index !== '' && savedFilter.index !== 'Select') {
                    setTimeout(() => getNames(), 0);
                } else {
                    // Otherwise just call getNames once to initialize
                    setTimeout(() => getNames(), 0);
                }
            } else {
                localStorage.setItem('namesFilter', JSON.stringify(filter));
                setTimeout(() => getNames(), 0);
            }
        }
    }, [namesData]);

    useEffect(() => {
        // Call getNames when filter changes after initial load
        if (names.length > 0 && filter.index !== '') {
            getNames();
        }
    }, [filter, names]);

    const filterChanged = (newFilter) => {
        // if the index no longer matches the type, change it
        localStorage.setItem('namesFilter', JSON.stringify(newFilter));
        getNames(newFilter);
    };

    const getNames = (currentFilter) => {
        setShownNames({
            familyType: null,
            firstNames: [],
            lastNames: []
        });

        const filterToUse = currentFilter || filter;
        
        // Only proceed if we have a valid index selection
        if (!filterToUse.index || filterToUse.index === '' || filterToUse.index === 'Select') {
            return;
        }
        
        const availableNames = names.find(n => n.index === filterToUse.index);
        if (!availableNames) {
            return;
        }

        // Debug: log availableNames to see structure
        console.log('availableNames:', availableNames);

        let firstNames = [];
        let lastNames = [];

        switch (filterToUse.type) {
            case 'building':
                firstNames = availableNames.lists?.first || [];
                lastNames = availableNames.lists?.second || [];
                break;
            case 'race':
                firstNames = filterToUse.sex === 'female' ? availableNames.lists?.females : availableNames.lists?.males;
                if (availableNames.family_type) {
                    lastNames = availableNames.lists?.family || [];
                    setShownNames(prev => ({ ...prev, familyType: availableNames.family_type }));
                }
                break;
            default:
                firstNames = [];
                lastNames = [];
        }

        console.log('firstNames:', firstNames, 'lastNames:', lastNames);

        switch (filterToUse.used) {
            case 'available':
                setShownNames(prev => ({
                    ...prev,
                    firstNames: (firstNames || []).filter(n => !namesUsed.includes(n)),
                    lastNames: (lastNames || []).filter(n => !namesUsed.includes(n))
                }));
                break;
            case 'used':
                setShownNames(prev => ({
                    ...prev,
                    firstNames: (firstNames || []).filter(n => namesUsed.includes(n)),
                    lastNames: (lastNames || []).filter(n => namesUsed.includes(n))
                }));
                break;
            default:
                setShownNames(prev => ({
                    ...prev,
                    firstNames: firstNames || [],
                    lastNames: lastNames || []
                }));
        }
    };

    const isNameUsed = (name) => {
        return namesUsed.includes(name);
    };

    const toggleUsed = (name) => {
        // If the name is in the list, remove it otherwise add it
        setNamesUsed(prev => {
            const index = prev.indexOf(name);
            let newUsed;
            if (index === -1) {
                newUsed = [...prev, name];
            } else {
                newUsed = prev.filter(n => n !== name);
            }
            localStorage.setItem('namesUsed', JSON.stringify(newUsed));
            return newUsed;
        });
    };

    const typeChanged = (newFilter) => {
        setFilter(prev => ({ ...prev, index: 'Select' }));
        filterChanged(newFilter);
    };

    if (loading) {
        return <div className="list"><div>Loading names...</div></div>;
    }

    return (
        <div className="names-table">
            <NameFilterForm filter={filter} setFilter={setFilter} filterChanged={filterChanged} />
            <br/>
            {shownNames.firstNames && shownNames.firstNames.length > 0 && (
                <NameListTable filter={filter} shownNames={shownNames} isNameUsed={isNameUsed} toggleUsed={toggleUsed} />
            )}
        </div>
    );
}

export default Names;

// src/app/components/names/names.component.ts
﻿import { Component, OnDestroy, OnInit } from '@angular/core';
import { combineLatest, Subscription } from 'rxjs';

import { DataService } from '../../services/data.service';

@Component({
    selector: 'race-names',
    styleUrls: ['./names.component.css'],
    templateUrl: './names.component.html',
    standalone: false
})
export class NamesComponent implements OnInit, OnDestroy {
  names: any[] = [];
  namesUsed: string[] = [];
  shownNames = {
    familyType: null,
    firstNames: [],
    lastNames: []
  };
  filter = {
    index: 'Select',
    type: 'Select', // race or building
    sex: 'Select',
    used: 'All'
  }
  subscriptions: Subscription[] = [];

  constructor(public dataService: DataService) { }

  ngOnInit(): void {
    this.subscriptions.push(combineLatest([
      this.dataService.getNames()
    ]).subscribe((data: any) => {
      this.names = data[0];
      // Set search filters
      let filterJson = localStorage.getItem('namesFilter');
      if(filterJson) {
        this.filter = JSON.parse(filterJson);
      } else {
        localStorage.setItem('namesFilter', JSON.stringify(this.filter));
      }
      // Set used names
      let namesUsedJson = localStorage.getItem('namesUsed');
      if(namesUsedJson != null) {
        this.namesUsed = JSON.parse(namesUsedJson);
      }
      this.getNames();
    }));
  }

  ngOnDestroy(): void {
    // Unsubscribe all subscriptions to avoid memory leak
    this.subscriptions.forEach(subscription => subscription.unsubscribe());
  }

  filterChanged(): void {
    // if the index no longer matches the type, change it
    localStorage.setItem('namesFilter', JSON.stringify(this.filter));
    this.getNames();
  }

  getNames() {
    this.shownNames = {
      familyType: null,
      firstNames: [],
      lastNames: []
    };
    if(this.filter.index != 'Select') {
      const availableNames = this.names.find(n => n.index==this.filter.index);
      if(availableNames) {
        let firstNames = [];
        let lastNames = [];
        switch(this.filter.type) {
          case 'building':
            firstNames = availableNames.lists.first;
            lastNames = availableNames.lists.second;
            break;
          case 'race':
            firstNames = this.filter.sex=='female' ? availableNames.lists.females : availableNames.lists.males;
            if(availableNames.family_type) {
              lastNames = availableNames.lists.family;
              this.shownNames.familyType = availableNames.family_type;
            }
            break;
          default:
            firstNames = [];
            lastNames = [];
        }
        switch(this.filter.used){
          case 'available':        
            this.shownNames.firstNames = firstNames.filter((n: string) => !this.namesUsed.includes(n));
            this.shownNames.lastNames = lastNames.filter((n: string) => !this.namesUsed.includes(n));
            break;
          case 'used':
            this.shownNames.firstNames = firstNames.filter((n: string) => this.namesUsed.includes(n));
            this.shownNames.lastNames = lastNames.filter((n: string) => this.namesUsed.includes(n));
            break;
          default:
            this.shownNames.firstNames = firstNames;
            this.shownNames.lastNames = lastNames;
        }
      }
    }
    console.log(this.shownNames);
  }

  isNameUsed(name: string): boolean {
    return this.namesUsed.includes(name);
  }
  
  toggleUsed(name: string) {
    // If the name is in the list, remove it otherwise add it
    const index = this.namesUsed.indexOf(name);
    if(index == -1) {
      this.namesUsed.push(name);
    } else {
      this.namesUsed.splice(index, 1);
    }
    localStorage.setItem('namesUsed', JSON.stringify(this.namesUsed));
  }

  typeChanged(): void {
    this.filter.index = 'Select';
    this.filterChanged();
  }

}

﻿<div class="names">
  <form #searchForm="ngForm" novalidate>
    <!--Type-->
    <label for="type" class="col-form-label">Type</label>
    <select name="type" [(ngModel)]="filter.type" #categoryControl="ngModel" class="form-control" (ngModelChange)="filterChanged()">
      <option disabled>Select</option>
      <option value="building">Building</option>
      <option value="race">Race</option>
    </select>
    <!--Index-->
    <label for="index" class="col-form-label">@if (filter.type=='building') {
      <span>Building</span>
      }@if (filter.type=='race') {
      <span>Race</span>
    }</label>
    <select name="index" [(ngModel)]="filter.index" #categoryControl="ngModel" class="form-control" (ngModelChange)="filterChanged()">
      <option>Select</option>
      @if (filter.type=='building') {
        <option value="tavern">Tavern</option>
      }
      @if (filter.type=='race') {
        <option value="dragonborn">Dragonborn</option>
        <option value="dwarf">Dwarf</option>
        <option value="elf">Elf</option>
        <option value="gnome">Gnome</option>
        <option value="halfling">Halfling</option>
        <option value="half-orc">Half Orc</option>
        <option value="tiefling">Tiefling</option>
        <option value="human-celtic">Human (Celtic)</option>
      }
    </select>
    @if (filter.type=='race') {
      <!--Sex-->
      <label for="sex" class="col-form-label">Sex</label>
      <select name="sex" [(ngModel)]="filter.sex" #categoryControl="ngModel" class="form-control" (ngModelChange)="filterChanged()">
        <option disabled selected>Select</option>
        <option value="female">Female</option>
        <option value="male">Male</option>
      </select>
    }
    <!--Used-->
    <label for="used" class="col-form-label">Used</label>
    <select name="used" [(ngModel)]="filter.used" #bookmarkedControl="ngModel" class="form-control" (ngModelChange)="typeChanged()">
      <option selected>All</option>
      <option value="available">Available</option>
      <option value="used">Used</option>
    </select>
  </form>
  @if (shownNames.firstNames && shownNames.firstNames.length > 0) {
    <div class="list" [class.dualList]="filter.type=='building' || shownNames.familyType != null">
      <table class="table table-condensed table-striped table-hover">
        <thead>
          <tr>
            <th class="col-form-label">
              @if (filter.type=='race') {
                <span>First Names</span>
              }
              @if (filter.type=='building') {
                <span>First Part</span>
              }
            </th>
            <th class="col-form-label">Used</th>
          </tr>
        </thead>
        <tbody>
          @for (name of shownNames.firstNames; track name) {
            <tr>
              <td>{{name}}</td>
              <td>
                <input class="form-check-input" type="checkbox" (click)="toggleUsed(name)" [checked]="isNameUsed(name)">
              </td>
            </tr>
          }
        </tbody>
      </table>
      @if (filter.type=='building' || shownNames.familyType != null) {
        <table class="table table-condensed table-striped table-hover">
          <thead>
            <tr>
              <th class="col-form-label">
                @if (filter.type=='race') {
                  <span>{{shownNames.familyType}} Names</span>
                }
                @if (filter.type=='building') {
                  <span>Last Part</span>
                }
              </th>
              <th class="col-form-label">Used</th>
            </tr>
          </thead>
          <tbody>
            @for (name of shownNames.lastNames; track name) {
              <tr>
                <td>{{name}}</td>
                <td>
                  <input class="form-check-input" type="checkbox" (click)="toggleUsed(name)" [checked]="isNameUsed(name)">
                </td>
              </tr>
            }
          </tbody>
        </table>
      }
    </div>
  }
</div>
