// src/components/rules/Feat.jsx
function Feat({ feat, expand, onExpand }) {
    const isExpanded = !!expand;

    const toggleDetails = () => {
        onExpand(!isExpanded);
    };

    if (!feat) {
        return null;
    }

    return (
        <div className={`card w-100 ${isExpanded ? 'active' : ''}`} id={feat.index}>
            <div className="card-header clickable" onClick={toggleDetails}>
                <div className="card-title">{feat.name}</div>
            </div>
            {isExpanded && (
                <div className="card-body">
                    <div className="card-text">
                        {feat.prerequisite && (
                            <div>
                                <b>Prerequisite</b>: {feat.prerequisite}<br /><br />
                            </div>
                        )}
                        {feat.desc && feat.desc.map((desc) => (
                            <span key={desc}>
                                {desc}<br /><br />
                            </span>
                        ))}
                        {feat.benefits && feat.benefits.length > 0 && (
                            <ul>
                                {feat.benefits.map((benefit) => (
                                    <li key={benefit}>{benefit}</li>
                                ))}
                            </ul>
                        )}
                    </div>
                </div>
            )}
        </div>
    );
}

export default Feat;

// src/app/components/rules/feat/feat.component.ts
﻿import { Component, Input, Output, EventEmitter } from '@angular/core';

@Component({
    selector: 'app-feat',
    styleUrls: ['./feat.component.css'],
    templateUrl: './feat.component.html',
    standalone: false
})
export class FeatComponent {

  @Input() feat: any = null;
  @Input() expand = false;
  @Output() expanded = new EventEmitter<boolean>();

  toggleDetails() {
    this.expand = !this.expand;
    this.expanded.emit(this.expand);
  }

}

﻿@if (feat != null) {
  <div class="card w-100" [class.active]="expand">
    <div class="card-header clickable" (click)="toggleDetails()">
      <div class="card-title">{{feat.name}}</div>
    </div>
    @if (expand) {
      <div class="card-body">
        <div class="card-text removeExtraLine">
          @if (feat.prerequisite) {
            <div>
              <b>Prerequisite</b>: {{feat.prerequisite}}<br /><br />
            </div>
          }
          @for (desc of feat.desc; track desc) {
            <span>
              {{desc}}<br /><br />
            </span>
          }
          @if (feat.benefits) {
            <ul>
              @for (benefit of feat.benefits; track benefit) {
                <li>{{benefit}}</li>
              }
            </ul>
          }
        </div>
      </div>
    }
  </div>
}
