// src/app/components/magic-item/magic-item.component.ts
﻿import { Component, EventEmitter, Input, Output } from '@angular/core';
import { DomSanitizer } from '@angular/platform-browser';

@Component({
    selector: 'magic-item',
    styleUrls: ['./magic-item.component.css'],
    templateUrl: './magic-item.component.html',
    standalone: false
})
export class MagicItemComponent {

  @Input() expand = false;
  @Input() magicItem: any = null;
  @Output() readonly bookmarkChanged = new EventEmitter<boolean>(); // Bubble up that the magicItem is bookmarked for the current session
  @Output() expanded = new EventEmitter<boolean>();
  
  constructor(public domSanitizer: DomSanitizer) {}

  toggleDetails() {
    this.expand = !this.expand;
    this.expanded.emit(this.expand);
  }

  toggleBookmark(magicItem: any) {
    magicItem.bookmarked = !magicItem.bookmarked;
    this.bookmarkChanged.emit(magicItem.bookmarked);
  }

}

﻿@if (magicItem != null) {
  <div class="card w-100" [class.active]="expand">
    <div class="card-header clickable">
      <div (click)="toggleDetails()">
        <div class="card-title">{{magicItem.name}}</div>
        <i>{{magicItem.type}}@if (magicItem.subtype) {
          <span> ({{magicItem.subtype}})</span>
          }, {{magicItem.rarity}} @if (magicItem.requiresAttunement && !magicItem.attunementRequirements) {
          <span> (requires attunement)</span>
          }@if (magicItem.requiresAttunement && magicItem.attunementRequirements) {
          <span> ({{magicItem.attunementRequirements}})</span>
        }</i><br />
      </div>
      <div class="form-check">
        <input class="form-check-input" type="checkbox" id="bookmarked" name="bookmarked" [(ngModel)]="magicItem.bookmarked" #bookmarkedControl="ngModel" (click)="toggleBookmark(magicItem)">
        <label class="form-check-label" for="bookmarked">
          Bookmarked
        </label>
      </div>
    </div>
    @if (expand) {
      <div class="card-body">
        @let descArray = magicItem.desc || (magicItem.description ? [magicItem.description] : []);
        @for (desc of descArray; track desc; let i = $index) {
          <span>
            @if (i > 0) {
              <span [innerHtml]="domSanitizer.bypassSecurityTrustHtml(desc)"></span>
            } @else {
              <span [innerHtml]="domSanitizer.bypassSecurityTrustHtml(desc)"></span>
            }
          </span>
        }
      </div>
    }
  </div>
}

// src/components/magic-items/MagicItem.jsx
import { useState, useEffect } from 'react';
import './MagicItem.css';

function MagicItem({ magicItem, expand, onExpand, onBookmarkChange }) {
    const [isExpanded, setIsExpanded] = useState(expand);

    // Update local state when prop changes
    useEffect(() => {
        if (expand !== isExpanded) {
            setIsExpanded(expand);
        }
    }, [expand]);

    const toggleDetails = () => {
        setIsExpanded(!isExpanded);
        onExpand(!isExpanded);
    };

    const toggleBookmark = () => {
        magicItem.bookmarked = !magicItem.bookmarked;
        onBookmarkChange(magicItem.index, magicItem.bookmarked);
    };

    const handleCheckboxChange = (e) => {
        e.stopPropagation();
        e.nativeEvent.stopImmediatePropagation();
        magicItem.bookmarked = e.target.checked;
        onBookmarkChange(magicItem.index, magicItem.bookmarked);
    };

    const handleLabelClick = (e) => {
        e.stopPropagation();
        e.nativeEvent.stopImmediatePropagation();
    };

    if (!magicItem) {
        return null;
    }

    return (
        <div className={`card w-100 ${isExpanded ? 'active' : ''}`} id={magicItem.index}>
            <div className="card-header clickable">
                <div onClick={toggleDetails}>
                    <div className="card-title">{magicItem.name}</div>
                    <div>
                        <i>{magicItem.type}, {magicItem.rarity}</i>
                        {magicItem.requiresAttunement && (
                            <span>, Requires Attunement</span>
                        )}
                    </div>
                </div>
                <div className="form-check">
                    <input 
                        className="form-check-input" 
                        type="checkbox" 
                        id={`bookmarked-${magicItem.index}`}
                        checked={magicItem.bookmarked || false}
                        onChange={handleCheckboxChange}
                    />
                    <label 
                        className="form-check-label" 
                        htmlFor={`bookmarked-${magicItem.index}`}
                        onClick={handleLabelClick}
                    >
                        Bookmarked
                    </label>
                </div>
            </div>

            {isExpanded && (
                <div className="card-body">
                    <div className="card-text">
                        {/* Description */}
                        {magicItem.description && (
                            <div className="removeExtraLine">
                                <b>Description:</b><br />
                                {magicItem.description}
                            </div>
                        )}

                        {/* Subtype */}
                        {magicItem.subtype && (
                            <div>
                                <b>Subtype:</b>&nbsp;{magicItem.subtype}<br />
                            </div>
                        )}
                    </div>
                </div>
            )}
        </div>
    );
}

export default MagicItem;
