// src/app/components/locations/locations.component.ts
﻿import { Component, OnDestroy, OnInit } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { combineLatest, Subscription } from 'rxjs';
import { DomSanitizer } from '@angular/platform-browser';

import { DataService } from '../../services/data.service';
declare const utils: any // Javascript utilities

@Component({
    selector: 'locations-lore',
    styleUrls: ['./locations.component.css'],
    templateUrl: './locations.component.html',
    standalone: false
})
export class LocationsComponent implements OnInit, OnDestroy {
    image = '';
    locations: any[] = [];
    subscriptions: Subscription[] = [];
    shownCard = '';

    constructor(private route: ActivatedRoute, private router: Router, public domSanitizer: DomSanitizer, public dataService: DataService) { }

    ngOnInit(): void {
        window.history.forward();
        this.subscriptions.push(combineLatest([
            this.dataService.getLocations()
        ]).subscribe((data: any) => {
            this.locations = data[0];
            const index = this.route.snapshot.queryParamMap.get('index');
            if (index) {
                const location = this.locations.find((location) => location.index === index);
                if (location) {
                    this.expandCard(index);
                    utils.scrollIntoView(location.index);
                }
            }
        }));
    }

    ngOnDestroy(): void {
        // Unsubscribe all subscriptions to avoid memory leak
        this.subscriptions.forEach(subscription => subscription.unsubscribe());
    }

    expandCard(index: string) {
        if (this.shownCard == index) {
            this.shownCard = '';
        } else {
            this.shownCard = index;
            utils.scrollIntoView(index);
        }
        this.router.navigate([], {
            queryParams: { index: index },
            queryParamsHandling: 'merge',
        });
    }

}

﻿@if (image!='') {
  <div class="cover" (click)="image=''">
    <img [src]="'assets/locations/' + image">
  </div>
}
@for (location of locations; track location) {
  <div class="list" [id]="location.index">
    <div class="card outer w-100" [class.active]="shownCard==location.index" [id]="location.index">
      <div class="card-header clickable" (click)="expandCard(location.index)">
        <div>
          <div class="card-title">{{location.name}}</div>
          <i>{{location.type}}</i><br />
        </div>
      </div>
      @if (shownCard == location.index) {
        <div class="card-body">
          <div class="stats">
            <div>
              <!-- no stats -->
            </div>
            <div>
              @if (location.image) {
                <button type="button" class="btn btn-primary" (click)="image=location.image">Image</button>
              }
            </div>
          </div>
          <div [innerHtml]="domSanitizer.bypassSecurityTrustHtml(location.desc)"></div>
          <br/>
          {{location.book}} (page {{location.page}})
        </div>
      }
    </div>
  </div>
}

// src/components/Locations.jsx

import { useState, useEffect } from 'react';
import { useSearchParams } from 'react-router-dom';
import { useLocations } from '../data/dataService.js';
import { scrollIntoView } from '../data/utils';
import { renderHtmlContent } from '../utils/htmlUtils';
import './Locations.css';
import './common/Cover.css';

function Locations() {
    const [image, setImage] = useState('');
    const [searchParams, setSearchParams] = useSearchParams();

    // Derive shownCard from URL params
    const shownCard = searchParams.get('index') || '';

    // Scroll to shown card when it changes
    useEffect(() => {
        if (shownCard) {
            requestAnimationFrame(() => scrollIntoView(shownCard));
        }
    }, [shownCard]);

    // Fetch data
    const { data: locationsData, loading } = useLocations();

    const expandCard = (index) => {
        if (shownCard === index) {
            // Close the card
            setSearchParams({});
        } else {
            // Open the card
            setSearchParams({ index });
        }
    };

    const showImage = (locationIndex) => {
        // Show full-screen image when clicking the Image button
        const location = locationsData.find(loc => loc.index === locationIndex);
        if (location && location.image) {
            setImage(`${import.meta.env.BASE_URL}images/${location.image}`);
        }
    };

    if (loading) {
        return <div className="list"><div>Loading locations...</div></div>;
    }

    return (
        <>
            {image && (
                <div className="cover-overlay" onClick={() => setImage('')}>
                    {image && (
                        <img src={image} alt="Location map" />
                    )}
                </div>
            )}
            
            <div className="list">
                {locationsData.map((location) => (
                    <div key={location.index} id={location.index}>
                        {/* Scroll anchor - must be in document flow */}
                        <div
                            id={`scroll-anchor-${location.index}`}
                            className="locations-scroll-anchor"
                        ></div>
                        <div 
                            className={`card outer w-100 ${shownCard === location.index ? 'active' : ''}`} 
                            id={location.index}
                        >
                            <div 
                                className="card-header clickable" 
                                id={`${location.index}-header`}
                                onClick={() => expandCard(location.index)}
                            >
                                <div>
                                    <div className="card-title">{location.name}</div>
                                    <i>{location.type}</i><br />
                                </div>
                            </div>
                            
                            {shownCard === location.index && (
                                <div className="card-body" id={`${location.index}-body`}>
                                    <div className="location-stats">
                                        <div>
                                            {/* no stats */}
                                        </div>
                                        <div>
                                            {location.image && (
                                                <button 
                                                    type="button" 
                                                    className="btn btn-primary" 
                                                    onClick={(e) => {
                                                        e.stopPropagation();
                                                        showImage(location.index);
                                                    }}
                                                >
                                                    Image
                                                </button>
                                            )}
                                        </div>
                                    </div>
                                    <div dangerouslySetInnerHTML={renderHtmlContent(location.description)}></div>
                                    <br />
                                    {location.book && `(${location.book} page ${location.page})`}
                                </div>
                            )}
                        </div>
                    </div>
                ))}
            </div>
        </>
    );
}

export default Locations;
