// src/app/components/monsters/monster-search/monster-search.component.ts
﻿import { Component, OnDestroy, OnInit } from '@angular/core';
import { combineLatest, Subscription } from 'rxjs';

import { DataService } from '../../../services/data.service';

@Component({
  selector: 'monster-search',
  styleUrls: ['./monster-search.component.scss'],
  templateUrl: './monster-search.component.html'
})
export class MonsterSearchComponent implements OnInit, OnDestroy {
  filter = {
    bookmarked: 'All',
    challengeRatingMin: 0,
    challengeRatingMax: 25,
    environment: 'All',
    name: '',
    size: 'All',
    type: 'All',
    xpMin: 0,
    xpMax: 50000,
  }
  monsters: any[] = [];
  shownCard = '';
  subscriptions: Subscription[] = [];

  constructor(public dataService: DataService) { }

  ngOnInit(): void {
    this.subscriptions.push(combineLatest([
      this.dataService.getMonsters()
    ]).subscribe((data: any) => {
      this.monsters = data[0];
      console.log(`${this.monsters.length} monsters`);
      // console.log('monsters missing images listed below:');
      // console.log(this.monsters.filter(m => m.image!=true));
      // Set search filters
      let filter = localStorage.getItem('monsterFilter');
      if(filter) {
        this.filter = JSON.parse(filter);
      } else {
        localStorage.setItem('monsterFilter', JSON.stringify(this.filter));
      }
      // Set bookmarked monsters
      let monstersBookmarkedJson = localStorage.getItem('monstersBookmarked');
      let monstersBookmarked: string[] = [];
      if(monstersBookmarkedJson != null) {
        monstersBookmarked = JSON.parse(monstersBookmarkedJson);
      }
      this.monsters.forEach(monster => {
        monster.bookmarked = monstersBookmarked.includes(monster.index);
      })
    }));
  }

  ngOnDestroy(): void {
    // Unsubscribe all subscriptions to avoid memory leak
    this.subscriptions.forEach(subscription => subscription.unsubscribe());
  }

  expandCard(index: string, expanded: boolean) {
    if(expanded) {
      this.shownCard=index;
    }
  }
  
  filterChanged(): void {
    localStorage.setItem('monsterFilter', JSON.stringify(this.filter));
  }

  saveBookmark() {
    let monstersBookmarked: string[] = [];
    this.monsters.forEach(monster => {
      if(monster.bookmarked == true) {
        monstersBookmarked.push(monster.index);
      }
    })
    localStorage.setItem('monstersBookmarked', JSON.stringify(monstersBookmarked));
  }

  showMonster(monster: any) {
    // Bookmarked filter
    if (this.filter.bookmarked != 'All' && !monster.bookmarked) {
      return false;
    }
    // Challenge Range
    if (monster.challenge_rating < this.filter.challengeRatingMin || monster.challenge_rating > this.filter.challengeRatingMax) {
      return false;
    }
    // Environment filter
    if (this.filter.environment != 'All' &&  (!monster.environments || !monster.environments.includes(this.filter.environment))) {
      return false;
    }
    // Name filter
    if (this.filter.name != '' &&  !monster.name.toLowerCase().includes(this.filter.name.toLowerCase())) {
      return false;
    }
    // Size filter
    if (this.filter.size != 'All' && this.filter.size != monster.size) {
      return false;
    }
    // Type filter
    if (this.filter.type != 'All' && this.filter.type != monster.type) {
      return false;
    }
    // XP
    if (monster.xp < this.filter.xpMin || monster.xp > this.filter.xpMax) {
      return false;
    }
    return true;
  }

}

﻿<form #searchForm="ngForm" novalidate>
	<!--Name-->
	<label for="name" class="col-form-label">Name</label>
	<div [class.has-error]="nameControl.invalid && nameControl.dirty">
		<input type="text" class="form-control" id="name" name="name" [(ngModel)]="filter.name" #nameControl="ngModel" (ngModelChange)="filterChanged()" pattern="[A-Za-z ]+" maxlength="50">
		<div [hidden]="nameControl.valid || nameControl.pristine" class="alert alert-danger">
			Name should be less than 50 characters
		</div>
	</div>
	<!--Challenge Range-->
	<label for="challengeRatingMin" class="col-form-label">Challenge Rating</label>
	<div class="row" [class.has-error]="challengeRatingMinControl.invalid && challengeRatingMinControl.dirty || challengeRatingMaxControl.invalid && challengeRatingMaxControl.dirty">
		<div class="col">
			<input type="number" class="column form-control" id="challengeRatingMin" name="challengeRatingMin" [(ngModel)]="filter.challengeRatingMin" #challengeRatingMinControl="ngModel" (ngModelChange)="filterChanged()" min="0" max="25" step="0.25" autofocus placeholder="min">
		</div>
		<div class="col">
			<input type="number" class="column form-control" id="challengeRatingMax" name="challengeRatingMax" [(ngModel)]="filter.challengeRatingMax" #challengeRatingMaxControl="ngModel" (ngModelChange)="filterChanged()" min="0" max="25" step="0.25" placeholder="max">
		</div>
		<div class="col alert alert-danger" [hidden]="challengeRatingMinControl.valid || challengeRatingMinControl.pristine || challengeRatingMaxControl.valid || challengeRatingMaxControl.pristine">
			Challenge Rating should be between 0 and 25
		</div>
	</div>
	<!--XP-->
	<label for="xpMin" class="col-form-label">XP</label>
	<div class="row" [class.has-error]="xpMinControl.invalid && xpMinControl.dirty || xpMaxControl.invalid && xpMaxControl.dirty">
		<div class="col">
			<input type="number" class="column form-control" id="xpMin" name="xpMin" [(ngModel)]="filter.xpMin" #xpMinControl="ngModel" (ngModelChange)="filterChanged()" min="0" max="50000" step="25" autofocus placeholder="min">
		</div>
		<div class="col">
			<input type="number" class="column form-control" id="xpMax" name="xpMax" [(ngModel)]="filter.xpMax" #xpMaxControl="ngModel" (ngModelChange)="filterChanged()" min="0" max="50000" step="25" placeholder="max">
		</div>
		<div class="col alert alert-danger" [hidden]="xpMinControl.valid || xpMinControl.pristine || xpMaxControl.valid || xpMaxControl.pristine">
			XP should be between 0 and 50000
		</div>
	</div>
	<!--Environment-->
	<label for="environment" class="col-form-label">Environment</label>
	<select name="environment" [(ngModel)]="filter.environment" #typeControl="ngModel" class="form-control" (ngModelChange)="filterChanged()">
		<option selected>All</option>
		<option value="arctic">Arctic</option>
		<option value="coastal">Coastal</option>
		<option value="desert">Desert</option>
		<option value="forest">Forest</option>
		<option value="grassland">Grassland</option>
		<option value="hill">Hill</option>
		<option value="mountain">Mountain</option>
		<option value="swamp">Swamp</option>
		<option value="underdark">Underdark</option>
		<option value="underwater">Underwater</option>
		<option value="urban">Urban</option>
	</select>
	<!--Type-->
	<label for="type" class="col-form-label">Type</label>
	<select name="type" [(ngModel)]="filter.type" #typeControl="ngModel" class="form-control" (ngModelChange)="filterChanged()">
		<option selected>All</option>
		<option value="aberration">Aberration</option>
		<option value="beast">Beast</option>
		<option value="celestial">Celestial</option>
		<option value="construct">Construct</option>
		<option value="dragon">Dragon</option>
		<option value="elemental">Elemental</option>
		<option value="fey">Fey</option>
		<option value="fiend">Fiend</option>
		<option value="giant">Giant</option>
		<option value="humanoid">Humanoid</option>
		<option value="monstrosity">Monstrosity</option>
		<option value="ooze">Ooze</option>
		<option value="plant">Plant</option>
		<option value="undead">Undead</option>
	</select>
	<!--Size-->
	<label for="size" class="col-form-label">Size</label>
	<select name="size" [(ngModel)]="filter.size" #typeControl="ngModel" class="form-control" (ngModelChange)="filterChanged()">
		<option selected>All</option>
		<option>Tiny</option>
		<option>Small</option>
		<option>Medium</option>
		<option>Large</option>
		<option>Huge</option>
		<option>Gargantuan</option>
	</select>
	<!--Bookmarked-->
	<label for="bookmarked" class="col-form-label">Bookmarked</label>
	<select name="bookmarked" [(ngModel)]="filter.bookmarked" #bookmarkedControl="ngModel" class="form-control" (ngModelChange)="filterChanged()">
		<option selected>All</option>
		<option>Bookmarked</option>
	</select>
</form>
<div *ngFor="let monster of monsters" class="list">
	<app-monster *ngIf="showMonster(monster)" [monster]="monster" (bookmarkChanged)="saveBookmark()" [expand]="shownCard==monster.index" (expanded)="expandCard(monster.index, $event)"></app-monster>
</div>

// src/components/MonsterSearch.jsx
import { useState, useEffect } from 'react';
import { useLocation, useSearchParams } from 'react-router-dom';
import { useMonsters } from '../data/dataService';
import Monster from './Monster';

// Javascript utilities (matching Angular)
const utils = {
    scrollIntoView: function(index) {
        const element = document.getElementById(index);
        if (element) {
            element.scrollIntoView({ behavior: 'smooth', block: 'center' });
        }
    }
};

function MonsterSearch() {
    const [monsters, setMonsters] = useState([]);
    const [filter, setFilter] = useState({
        bookmarked: 'All',
        challengeRatingMin: 0,
        challengeRatingMax: 25,
        environment: 'All',
        name: '',
        size: 'All',
        type: 'All',
        xpMin: 0,
        xpMax: 50000,
    });
    const [shownCard, setShownCard] = useState('');
    const location = useLocation();
    const [searchParams, setSearchParams] = useSearchParams();

    // Fetch data
    const { data: monstersData, loading: monstersLoading } = useMonsters();

    useEffect(() => {
        if (monstersData && monstersData.length > 0) {
            setMonsters(monstersData);
            console.log(`${monstersData.length} monsters`);

            const index = searchParams.get('index');
            if (index) {
                const monster = monstersData.find((monster) => monster.index === index);
                if (monster) {
                    setShownCard(index);
                    utils.scrollIntoView(monster.index);
                }
            } else {
                // Set search filters from localStorage, only defaulting to "All" when there's no saved data
                const savedFilter = localStorage.getItem('monsterFilter');
                if (savedFilter) {
                    setFilter(JSON.parse(savedFilter));
                } else {
                    localStorage.setItem('monsterFilter', JSON.stringify(filter));
                }
            }

            // Set bookmarked monsters from localStorage
            const monstersBookmarkedJson = localStorage.getItem('monstersBookmarked');
            let monstersBookmarked = [];
            if (monstersBookmarkedJson) {
                monstersBookmarked = JSON.parse(monstersBookmarkedJson);
            }

            // Update bookmarked status for each monster
            const updatedMonsters = monstersData.map(monster => ({
                ...monster,
                bookmarked: monstersBookmarked.includes(monster.index)
            }));
            setMonsters(updatedMonsters);
        }
    }, [monstersData]);

    const expandCard = (index, expanded) => {
        if (expanded) {
            setShownCard(index);
            utils.scrollIntoView(index);
        }

        // Update URL query params using setSearchParams
        if (expanded) {
            setSearchParams({ index });
        } else {
            setSearchParams({});
        }
    };

    const filterChanged = (newFilter) => {
        localStorage.setItem('monsterFilter', JSON.stringify(newFilter));
    };

    const saveBookmark = () => {
        const monstersBookmarked = monsters
            .filter(monster => monster.bookmarked)
            .map(monster => monster.index);
        localStorage.setItem('monstersBookmarked', JSON.stringify(monstersBookmarked));
    };

    const showMonster = (monster) => {
        // Bookmarked filter
        if (filter.bookmarked !== 'All' && !monster.bookmarked) {
            return false;
        }
        // Challenge Range
        if (monster.challenge_rating < filter.challengeRatingMin || monster.challenge_rating > filter.challengeRatingMax) {
            return false;
        }
        // Environment filter
        if (filter.environment !== 'All' && (!monster.environments || !monster.environments.includes(filter.environment))) {
            return false;
        }
        // Name filter
        if (filter.name !== '' && !monster.name.toLowerCase().includes(filter.name.toLowerCase())) {
            return false;
        }
        // Size filter
        if (filter.size !== 'All' && filter.size !== monster.size) {
            return false;
        }
        // Type filter
        if (filter.type !== 'All' && filter.type !== monster.type) {
            return false;
        }
        // XP
        if (monster.xp < filter.xpMin || monster.xp > filter.xpMax) {
            return false;
        }
        return true;
    };

    const handleBookmarkChange = (index, isBookmarked) => {
        // Update local state immediately so UI reflects the change
        setMonsters(prevMonsters => 
            prevMonsters.map(monster => 
                monster.index === index ? { ...monster, bookmarked: isBookmarked } : monster
            )
        );
        
        // Save to localStorage - get current bookmarked items from state
        const monstersBookmarked = monsters
            .filter(monster => monster.bookmarked)
            .map(monster => monster.index);
        
        if (isBookmarked) {
            // Add to bookmarked list
            monstersBookmarked.push(index);
        } else {
            // Remove from bookmarked list
            const filtered = monstersBookmarked.filter(i => i !== index);
            localStorage.setItem('monstersBookmarked', JSON.stringify(filtered));
        }
        
        if (isBookmarked) {
            localStorage.setItem('monstersBookmarked', JSON.stringify(monstersBookmarked));
        }
    };

    if (monstersLoading) {
        return <div className="list"><div>Loading monsters...</div></div>;
    }

    const filteredMonsters = monsters.filter(showMonster);

    return (
        <>
            <form className="filter-form">
                {/* Name */}
                <label htmlFor="name" className="col-form-label">Name</label>
                <div className={`has-error ${filter.name && filter.name.length >= 50 ? 'invalid' : ''}`}>
                    <input 
                        type="text" 
                        className="form-control" 
                        id="name" 
                        name="name"
                        value={filter.name}
                        onChange={(e) => {
                            const newFilter = { ...filter, name: e.target.value };
                            setFilter(newFilter);
                            filterChanged(newFilter);
                        }}
                        pattern="[A-Za-z ]+" 
                        maxLength="50"
                    />
                    {filter.name && filter.name.length >= 50 && (
                        <div className="alert alert-danger">
                            Name should be less than 50 characters
                        </div>
                    )}
                </div>

                {/* Challenge Rating */}
                <label htmlFor="challengeRatingMin" className="col-form-label">Challenge Rating</label>
                <div className="row">
                    <div className="col">
                        <input 
                            type="number" 
                            className="column form-control" 
                            id="challengeRatingMin" 
                            name="challengeRatingMin"
                            value={filter.challengeRatingMin}
                            onChange={(e) => {
                                const newFilter = { ...filter, challengeRatingMin: parseFloat(e.target.value) || 0 };
                                setFilter(newFilter);
                                filterChanged(newFilter);
                            }}
                            min="0" 
                            max="25" 
                            step="0.25" 
                            placeholder="min"
                        />
                    </div>
                    <div className="col">
                        <input 
                            type="number" 
                            className="column form-control" 
                            id="challengeRatingMax" 
                            name="challengeRatingMax"
                            value={filter.challengeRatingMax}
                            onChange={(e) => {
                                const newFilter = { ...filter, challengeRatingMax: parseFloat(e.target.value) || 0 };
                                setFilter(newFilter);
                                filterChanged(newFilter);
                            }}
                            min="0" 
                            max="25" 
                            step="0.25" 
                            placeholder="max"
                        />
                    </div>
                </div>

                {/* XP */}
                <label htmlFor="xpMin" className="col-form-label">XP</label>
                <div className="row">
                    <div className="col">
                        <input 
                            type="number" 
                            className="column form-control" 
                            id="xpMin" 
                            name="xpMin"
                            value={filter.xpMin}
                            onChange={(e) => {
                                const newFilter = { ...filter, xpMin: parseInt(e.target.value) || 0 };
                                setFilter(newFilter);
                                filterChanged(newFilter);
                            }}
                            min="0" 
                            max="50000" 
                            step="25" 
                            placeholder="min"
                        />
                    </div>
                    <div className="col">
                        <input 
                            type="number" 
                            className="column form-control" 
                            id="xpMax" 
                            name="xpMax"
                            value={filter.xpMax}
                            onChange={(e) => {
                                const newFilter = { ...filter, xpMax: parseInt(e.target.value) || 0 };
                                setFilter(newFilter);
                                filterChanged(newFilter);
                            }}
                            min="0" 
                            max="50000" 
                            step="25" 
                            placeholder="max"
                        />
                    </div>
                </div>

                {/* Environment */}
                <label htmlFor="environment" className="col-form-label">Environment</label>
                <select 
                    name="environment" 
                    className="form-control"
                    value={filter.environment}
                    onChange={(e) => {
                        const newFilter = { ...filter, environment: e.target.value };
                        setFilter(newFilter);
                        filterChanged(newFilter);
                    }}
                >
                    <option>All</option>
                    <option value="arctic">Arctic</option>
                    <option value="coastal">Coastal</option>
                    <option value="desert">Desert</option>
                    <option value="forest">Forest</option>
                    <option value="grassland">Grassland</option>
                    <option value="hill">Hill</option>
                    <option value="mountain">Mountain</option>
                    <option value="swamp">Swamp</option>
                    <option value="underdark">Underdark</option>
                    <option value="underwater">Underwater</option>
                    <option value="urban">Urban</option>
                </select>

                {/* Type */}
                <label htmlFor="type" className="col-form-label">Type</label>
                <select 
                    name="type" 
                    className="form-control"
                    value={filter.type}
                    onChange={(e) => {
                        const newFilter = { ...filter, type: e.target.value };
                        setFilter(newFilter);
                        filterChanged(newFilter);
                    }}
                >
                    <option>All</option>
                    <option value="aberration">Aberration</option>
                    <option value="beast">Beast</option>
                    <option value="celestial">Celestial</option>
                    <option value="construct">Construct</option>
                    <option value="dragon">Dragon</option>
                    <option value="elemental">Elemental</option>
                    <option value="fey">Fey</option>
                    <option value="fiend">Fiend</option>
                    <option value="giant">Giant</option>
                    <option value="humanoid">Humanoid</option>
                    <option value="monstrosity">Monstrosity</option>
                    <option value="ooze">Ooze</option>
                    <option value="plant">Plant</option>
                    <option value="undead">Undead</option>
                </select>

                {/* Size */}
                <label htmlFor="size" className="col-form-label">Size</label>
                <select 
                    name="size" 
                    className="form-control"
                    value={filter.size}
                    onChange={(e) => {
                        const newFilter = { ...filter, size: e.target.value };
                        setFilter(newFilter);
                        filterChanged(newFilter);
                    }}
                >
                    <option>All</option>
                    <option>Tiny</option>
                    <option>Small</option>
                    <option>Medium</option>
                    <option>Large</option>
                    <option>Huge</option>
                    <option>Gargantuan</option>
                </select>

                {/* Bookmarked */}
                <label htmlFor="bookmarked" className="col-form-label">Bookmarked</label>
                <select 
                    name="bookmarked" 
                    className="form-control"
                    value={filter.bookmarked}
                    onChange={(e) => {
                        const newFilter = { ...filter, bookmarked: e.target.value };
                        setFilter(newFilter);
                        filterChanged(newFilter);
                    }}
                >
                    <option>All</option>
                    <option>Bookmarked</option>
                </select>
            </form>

            {/* Monsters List */}
            <div className="list">
                {filteredMonsters.map((monster) => (
                    <div key={monster.index} id={monster.index}>
                        {showMonster(monster) && (
                            <Monster 
                                monster={monster}
                                expand={shownCard === monster.index}
                                onExpand={(expanded) => expandCard(monster.index, expanded)}
                                onBookmarkChange={handleBookmarkChange}
                            />
                        )}
                    </div>
                ))}
            </div>
        </>
    );
}

export default MonsterSearch;
