// src/app/components/rules/player-class/player-class.component.ts
﻿import { Component, Input, Output, EventEmitter, OnChanges, SimpleChanges } from '@angular/core';
import { DomSanitizer } from '@angular/platform-browser';
import { cloneDeep, merge, uniqBy } from 'lodash';
declare const utils: any // Javascript utilities

@Component({
    selector: 'player-class',
    styleUrls: ['./player-class.component.scss'],
    templateUrl: './player-class.component.html'
})
export class PlayerClassComponent implements OnChanges {

    @Input() expand = false;
    @Input() playerClass: any = null;
    @Output() expanded = new EventEmitter<boolean>();
    classFeatures: any = null;
    subclassFeatures: any = null;
    shownLevel = 0;
    shownSubclass = '';

    constructor(public domSanitizer: DomSanitizer) { }

    ngOnChanges(changes: SimpleChanges): void {
    }

    getNameString(names: string[]) {
        let nameString = '';
        names.forEach((name: string) => {
            nameString += `${name}, `;
        });
        return nameString.substr(0, nameString.length - 2);
    }

    getPrerequisites(feature: any) {
        let prerequisitesText = '';
        feature.prerequisites.forEach((prerequisite: any) => {
            switch (prerequisite.type) {
                case 'feature':
                    prerequisitesText += `feature ${prerequisite.feature.substr(14)}, `;
                    break;
                case 'level':
                    break;
                case 'proficiency':
                    prerequisitesText += `proficiency ${prerequisite.proficiency.substr(19)}, `;
                    break;
                case 'Spell':
                    prerequisitesText += `spell ${prerequisite.spell.substr(12)}, `;
                    break;
            }
        });
        return prerequisitesText.substr(0, prerequisitesText.length - 2);
    }

    getSpells(spells: any) {
        let spellNames = '';
        let lastFeature = '';
        let lastLevel = '';
        spells.forEach((spell: any) => {
            let level = spell.prerequisites[0].index;
            const levelIndex = level.indexOf('-');
            level = level.substr(levelIndex + 1, 2);
            let feature = '';
            if (spell.prerequisites[1]) {
                feature = spell.prerequisites[1].name;
                if (feature != lastFeature) {
                    if (lastFeature != '') {
                        spellNames += `<br/><br/>`;
                    }
                    spellNames += `<b>${feature}</b>:<br/>`;
                }
            }
            if (level != lastLevel) {
                if (lastLevel != '' && feature == lastFeature) {
                    spellNames += `<br/>`;
                }
                spellNames += `Level ${level}: ${spell.spell.name}`;
            } else {
                spellNames += `, ${spell.spell.name}`;
            }
            lastFeature = feature;
            lastLevel = level;
        });
        return spellNames;
    }

    toggleDetails() {
        this.expand = !this.expand;
        this.expanded.emit(this.expand);
    }
    updateFeatures() {
        const classLevels = this.playerClass.class_levels.filter((classLevel: any) => classLevel.level <= this.shownLevel);
        // Go through levels highest to lowest so is an ability increases at higher levels, that is the one retained in the array
        this.classFeatures = [];
        for (let i = classLevels.length - 1; i >= 0; i--) {
            classLevels[i].features.forEach((feature: any) => {
                const featureSummary = {
                    name: feature.name,
                    description: feature.desc,
                    details: feature.details
                };
                if (!this.classFeatures.some((classFeature: any) => classFeature.name == feature.name)) {
                    this.classFeatures.push(featureSummary);
                }
            });
        }
        if (this.shownSubclass != '') {
            const subclassLevels = this.playerClass.subclasses.find((clonedSubclass: any) => clonedSubclass.index === this.shownSubclass).class_levels.filter((classLevel: any) => classLevel.level <= this.shownLevel);;
            this.subclassFeatures = [];
            for (let i = subclassLevels.length - 1; i >= 0; i--) {
                subclassLevels[i].features.forEach((feature: any) => {
                    const featureSummary = {
                        name: feature.name,
                        description: feature.desc,
                        details: feature.details
                    };
                    if (!this.subclassFeatures.some((subclassFeature: any) => subclassFeature.name == feature.name)) {
                        this.subclassFeatures.push(featureSummary);
                    }
                });
            }
        }
    }
    showLevel(level: any) {
        if (level == this.shownLevel) {
            this.shownLevel = 0;
        } else {
            this.shownLevel = level;
            this.updateFeatures();
            utils.scrollIntoView(level, 120);
        }
    }
    showSubclass(subclass: string) {
        if (subclass == this.shownSubclass) {
            this.shownSubclass = '';
        } else {
            this.shownSubclass = subclass;
            this.updateFeatures();
            utils.scrollIntoView(subclass, 120);
        }
    }

}

﻿<div *ngIf="playerClass != null" class="card outer w-100" [class.active]="expand">
	<div class="card-header clickable" (click)="toggleDetails()">
		<div class="card-title">{{playerClass.name}}</div>
	</div>
	<div *ngIf="expand" class="card-body">
		{{playerClass.desc}}<br /><br />
		<b>Hit Die:</b>&nbsp;d{{playerClass.hit_die}}<br />
		<div *ngIf="playerClass.proficiencies.length > 0">
			<b>Proficiencies:</b>&nbsp;{{getNameString(playerClass.proficiencies)}}<br />
		</div>
		<div *ngIf="playerClass.proficiency_choices.length > 0">
			<b>Proficiencies:</b>&nbsp;Choose {{playerClass.proficiency_choices[0].choose}} -
			{{getNameString(playerClass.proficiency_choices[0].from)}}
		</div>
		<div *ngIf="playerClass.saving_throws.length > 0">
			<b>Saving Throws:</b>&nbsp;{{getNameString(playerClass.saving_throws)}}<br />
		</div>
		<b>Starting Wealth:</b>&nbsp;{{playerClass.starting_wealth}}<br />
		<!-- Features that are not level specific -->
		<div *ngIf="playerClass.features.length > 0" class="card inner w-100">
			<div class="card-header clickable" (click)="shownLevel=0">
				<div class="card-title">Features</div>
			</div>
			<div class="card-body removeExtraLine" [class.hidden]="shownLevel != 0">
				<div *ngFor="let feature of playerClass.features" class="removeExtraLine">
					<b>{{feature.name}}:</b>&nbsp;
					<span *ngFor="let desc of feature.desc">
						{{desc}}<br />
					</span>
					<div *ngIf="feature.prerequisites.length > 0">
						<b>Prerequisites:</b>&nbsp;{{getPrerequisites(feature)}}<br />
						<br />
					</div>
					<br />
				</div>
			</div>
		</div>
		<br />
		<b>Choose Level</b>:
		<div class="level-group">
			<div *ngFor="let level of playerClass.class_levels" class="btn-group">
				<button type="button" [class.active]="shownLevel==level.level" class="btn btn-outline-primary btn-level"
					(click)="showLevel(level.level)">{{level.level}}</button>
			</div>
		</div>
		<div class="subtext">
			<!-- Class Stats by Level -->
			<div *ngFor="let level of playerClass.class_levels" [id]="shownLevel">
				<div *ngIf="level.level==shownLevel">
					<div *ngIf="level.ability_score_bonuses > 0">
						<b>Ability Score Bonuses:</b>&nbsp;{{level.ability_score_bonuses}}<br />
					</div>
					<b>Proficiency Bonus:</b>&nbsp;{{level.prof_bonus}}<br />
					<div *ngIf="playerClass.index=='barbarian'">
						<b>Rage Count:</b>&nbsp;{{level.class_specific.rage_count}}<br />
						<b>Rage Damage Bonus:</b>&nbsp;{{level.class_specific.rage_damage_bonus}}<br />
						<div *ngIf="level.class_specific.brutal_critical_dice > 0">
							<b>Brutal Critical Dice:</b>&nbsp;{{level.class_specific.brutal_critical_dice}}<br />
						</div>
					</div>
					<div *ngIf="playerClass.index=='bard'">
						<b>Bardic Inspiration Die:</b>&nbsp;d{{level.class_specific.bardic_inspiration_die}}<br />
						<div *ngIf="level.class_specific.song_of_rest_die > 0">
							<b>Song of Rest Die:</b>&nbsp;d{{level.class_specific.song_of_rest_die}}<br />
						</div>
						<div *ngIf="level.class_specific.magical_secrets_max_5 > 0">
							<b>Magical Secrets:</b><br />
							&nbsp;&nbsp;&nbsp;&nbsp;{{level.class_specific.magical_secrets_max_5}} of level 5 or
							below<br />
						</div>
						<div *ngIf="level.class_specific.magical_secrets_max_7 > 0">
							&nbsp;&nbsp;&nbsp;&nbsp;{{level.class_specific.magical_secrets_max_7}} of level 7 or
							below<br />
						</div>
						<div *ngIf="level.class_specific.magical_secrets_max_9 > 0">
							&nbsp;&nbsp;&nbsp;&nbsp;{{level.class_specific.magical_secrets_max_9}} of level 9 or
							below<br />
						</div>
					</div>
					<div *ngIf="playerClass.index=='cleric'">
						<div *ngIf="level.class_specific.channel_divinity_charges > 0">
							<b>Channel Divinity
								Charges:</b>&nbsp;{{level.class_specific.channel_divinity_charges}}<br />
						</div>
						<div *ngIf="level.class_specific.destroy_undead_cr > 0">
							<b>Destroy Undead CR:</b>&nbsp;{{level.class_specific.destroy_undead_cr}}<br />
						</div>
					</div>
					<div *ngIf="playerClass.index=='druid' && level.class_specific.wild_shape_max_cr > 0">
						<b>Wild Shape Max CR:</b>&nbsp;{{level.class_specific.wild_shape_max_cr}}
						<span *ngIf="!level.class_specific.wild_shape_swim">&nbsp;(no flying of swimming speed)</span>
						<span
							*ngIf="level.class_specific.wild_shape_swim && !level.class_specific.wild_shape_fly">&nbsp;(no
							flying speed)</span>
						<br />
					</div>
					<div *ngIf="playerClass.index=='fighter'">
						<div *ngIf="level.class_specific.action_surges > 0">
							<b>Action Surges:</b>&nbsp;{{level.class_specific.action_surges}}<br />
						</div>
						<div *ngIf="level.class_specific.indomitable_uses > 0">
							<b>Indomitable Uses:</b>&nbsp;{{level.class_specific.indomitable_uses}}<br />
						</div>
						<div *ngIf="level.class_specific.extra_attacks > 0">
							<b>Extra Attacks:</b>&nbsp;{{level.class_specific.extra_attacks}}<br />
						</div>
					</div>
					<div *ngIf="playerClass.index=='monk'">
						<b>Martial
							Arts:</b>&nbsp;{{level.class_specific.martial_arts.dice_count}}d{{level.class_specific.martial_arts.dice_value}}<br />
						<div *ngIf="level.class_specific.ki_points > 0">
							<b>Ki Points:</b>&nbsp;{{level.class_specific.ki_points}}<br />
						</div>
						<div *ngIf="level.class_specific.unarmored_movement > 0">
							<b>Unarmored Movement:</b>&nbsp;{{level.class_specific.unarmored_movement}}<br />
						</div>
					</div>
					<div *ngIf="playerClass.index=='paladin' && level.class_specific.aura_range > 0">
						<b>Aura Range:</b>&nbsp;{{level.class_specific.aura_range}}<br />
					</div>
					<div *ngIf="playerClass.index=='ranger'">
						<b>Favored Enemies:</b>&nbsp;{{level.class_specific.favored_enemies}}<br />
						<b>Favored Terrain:</b>&nbsp;{{level.class_specific.favored_terrain}}<br />
					</div>
					<div *ngIf="playerClass.index=='rogue'">
						<b>Sneak
							Attack:</b>&nbsp;{{level.class_specific.sneak_attack.dice_count}}d{{level.class_specific.sneak_attack.dice_value}}<br />
					</div>
					<div *ngIf="playerClass.index=='sorcerer'">
						<div *ngIf="level.class_specific.sorcery_points > 0">
							<b>Sorcery Points:</b>&nbsp;{{level.class_specific.sorcery_points}}<br />
						</div>
						<div *ngIf="level.class_specific.metamagic_known > 0">
							<b>Metamagic Known:</b>&nbsp;{{level.class_specific.metamagic_known}}<br />
						</div>
						<div *ngIf="level.class_specific.creating_spell_slots.length > 0">
							<b>Creating Spell Slots:</b><br />
							<span *ngFor="let spellSlot of level.class_specific.creating_spell_slots">
								&nbsp;&nbsp;&nbsp;&nbsp;Level {{spellSlot.spell_slot_level}} Point Cost =
								{{spellSlot.sorcery_point_cost}}<br />
							</span>
						</div>
					</div>
					<div *ngIf="playerClass.index=='warlock'">
						<div *ngIf="level.class_specific.invocations_known > 0">
							<b>Invocations Known:</b>&nbsp;{{level.class_specific.invocations_known}}<br />
						</div>
						<div
							*ngIf="(level.class_specific.mystic_arcanum_level_6 && level.class_specific.mystic_arcanum_level_6 > 0) || (level.class_specific.mystic_arcanum_level_7 && level.class_specific.mystic_arcanum_level_7 > 0) || (level.class_specific.mystic_arcanum_level_8 && level.class_specific.mystic_arcanum_level_8 > 0) || (level.class_specific.mystic_arcanum_level_9 && level.class_specific.mystic_arcanum_level_9 > 0)">
							<b>Mystic Arcanum:</b><br />
							<div
								*ngIf="level.class_specific.mystic_arcanum_level_6 && level.class_specific.mystic_arcanum_level_6 > 0">
								&nbsp;&nbsp;&nbsp;&nbsp;Level 6 = {{level.class_specific.mystic_arcanum_level_6}}<br />
							</div>
							<div
								*ngIf="level.class_specific.mystic_arcanum_level_7 && level.class_specific.mystic_arcanum_level_7 > 0">
								&nbsp;&nbsp;&nbsp;&nbsp;Level 7 = {{level.class_specific.mystic_arcanum_level_7}}<br />
							</div>
							<div
								*ngIf="level.class_specific.mystic_arcanum_level_8 && level.class_specific.mystic_arcanum_level_8 > 0">
								&nbsp;&nbsp;&nbsp;&nbsp;Level 8 = {{level.class_specific.mystic_arcanum_level_8}}<br />
							</div>
							<div
								*ngIf="level.class_specific.mystic_arcanum_level_9 && level.class_specific.mystic_arcanum_level_9 > 0">
								&nbsp;&nbsp;&nbsp;&nbsp;Level 9 = {{level.class_specific.mystic_arcanum_level_9}}<br />
							</div>
						</div>
					</div>
					<div *ngIf="playerClass.index=='wizard'">
						<b>Arcane Recovery Levels:</b>&nbsp;{{level.class_specific.arcane_recovery_levels}}<br />
					</div>
					<div *ngIf="level.spellcasting">
						<div *ngIf="level.spellcasting.cantrips_known">
							<b>Cantrips Known:</b>&nbsp;{{level.spellcasting.cantrips_known}}<br />
						</div>
						<div *ngIf="level.spellcasting.spells_known">
							<b>Spells Known:</b>&nbsp;{{level.spellcasting.spells_known}}<br />
						</div>
						<div
							*ngIf="level.spellcasting.spell_slots_level_1 && level.spellcasting.spell_slots_level_1 > 0">
							<b>Spell Slots:</b><br />
							&nbsp;&nbsp;&nbsp;&nbsp;{{level.spellcasting.spell_slots_level_1}} of level 1<br />
						</div>
						<div
							*ngIf="level.spellcasting.spell_slots_level_2 && level.spellcasting.spell_slots_level_2 > 0">
							&nbsp;&nbsp;&nbsp;&nbsp;{{level.spellcasting.spell_slots_level_2}} of level 2<br />
						</div>
						<div
							*ngIf="level.spellcasting.spell_slots_level_3 && level.spellcasting.spell_slots_level_3 > 0">
							&nbsp;&nbsp;&nbsp;&nbsp;{{level.spellcasting.spell_slots_level_3}} of level 3<br />
						</div>
						<div
							*ngIf="level.spellcasting.spell_slots_level_4 && level.spellcasting.spell_slots_level_4 > 0">
							&nbsp;&nbsp;&nbsp;&nbsp;{{level.spellcasting.spell_slots_level_4}} of level 4<br />
						</div>
						<div
							*ngIf="level.spellcasting.spell_slots_level_5 && level.spellcasting.spell_slots_level_5 > 0">
							&nbsp;&nbsp;&nbsp;&nbsp;{{level.spellcasting.spell_slots_level_5}} of level 5<br />
						</div>
						<div
							*ngIf="level.spellcasting.spell_slots_level_6 && level.spellcasting.spell_slots_level_6 > 0">
							&nbsp;&nbsp;&nbsp;&nbsp;{{level.spellcasting.spell_slots_level_6}} of level 6<br />
						</div>
						<div
							*ngIf="level.spellcasting.spell_slots_level_7 && level.spellcasting.spell_slots_level_7 > 0">
							&nbsp;&nbsp;&nbsp;&nbsp;{{level.spellcasting.spell_slots_level_7}} of level 7<br />
						</div>
						<div
							*ngIf="level.spellcasting.spell_slots_level_8 && level.spellcasting.spell_slots_level_8 > 0">
							&nbsp;&nbsp;&nbsp;&nbsp;{{level.spellcasting.spell_slots_level_8}} of level 8<br />
						</div>
						<div
							*ngIf="level.spellcasting.spell_slots_level_9 && level.spellcasting.spell_slots_level_9 > 0">
							&nbsp;&nbsp;&nbsp;&nbsp;{{level.spellcasting.spell_slots_level_9}} of level 9<br />
						</div>
					</div>
				</div>
			</div>
			<!-- Subclass Stats by Level -->
			<div *ngFor="let subclass of playerClass.subclasses">
				<div *ngIf="shownSubclass==subclass.index">
					<div *ngFor="let level of subclass.class_levels">
						<div *ngIf="level.spellcasting && level.level==shownLevel">
							<div *ngIf="level.spellcasting.cantrips_known">
								<b>Cantrips Known:</b>&nbsp;{{level.spellcasting.cantrips_known}}<br />
							</div>
							<div *ngIf="level.spellcasting.spells_known">
								<b>Spells Known:</b>&nbsp;{{level.spellcasting.spells_known}}<br />
							</div>
							<div
								*ngIf="level.spellcasting.spell_slots_level_1 && level.spellcasting.spell_slots_level_1 > 0">
								<b>Spell Slots:</b><br />
								&nbsp;&nbsp;&nbsp;&nbsp;{{level.spellcasting.spell_slots_level_1}} of level 1<br />
							</div>
							<div
								*ngIf="level.spellcasting.spell_slots_level_2 && level.spellcasting.spell_slots_level_2 > 0">
								&nbsp;&nbsp;&nbsp;&nbsp;{{level.spellcasting.spell_slots_level_2}} of level 2<br />
							</div>
							<div
								*ngIf="level.spellcasting.spell_slots_level_3 && level.spellcasting.spell_slots_level_3 > 0">
								&nbsp;&nbsp;&nbsp;&nbsp;{{level.spellcasting.spell_slots_level_3}} of level 3<br />
							</div>
							<div
								*ngIf="level.spellcasting.spell_slots_level_4 && level.spellcasting.spell_slots_level_4 > 0">
								&nbsp;&nbsp;&nbsp;&nbsp;{{level.spellcasting.spell_slots_level_4}} of level 4<br />
							</div>
							<div
								*ngIf="level.spellcasting.spell_slots_level_5 && level.spellcasting.spell_slots_level_5 > 0">
								&nbsp;&nbsp;&nbsp;&nbsp;{{level.spellcasting.spell_slots_level_5}} of level 5<br />
							</div>
							<div
								*ngIf="level.spellcasting.spell_slots_level_6 && level.spellcasting.spell_slots_level_6 > 0">
								&nbsp;&nbsp;&nbsp;&nbsp;{{level.spellcasting.spell_slots_level_6}} of level 6<br />
							</div>
							<div
								*ngIf="level.spellcasting.spell_slots_level_7 && level.spellcasting.spell_slots_level_7 > 0">
								&nbsp;&nbsp;&nbsp;&nbsp;{{level.spellcasting.spell_slots_level_7}} of level 7<br />
							</div>
							<div
								*ngIf="level.spellcasting.spell_slots_level_8 && level.spellcasting.spell_slots_level_8 > 0">
								&nbsp;&nbsp;&nbsp;&nbsp;{{level.spellcasting.spell_slots_level_8}} of level 8<br />
							</div>
							<div
								*ngIf="level.spellcasting.spell_slots_level_9 && level.spellcasting.spell_slots_level_9 > 0">
								&nbsp;&nbsp;&nbsp;&nbsp;{{level.spellcasting.spell_slots_level_9}} of level 9<br />
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
		<!-- Class features by Level -->
        <div class="subtext">
            <div *ngFor="let feature of classFeatures" class="removeExtraLine">
                <div class="feature">
                    <b>{{feature.name}}</b>:&nbsp;
                    <span [innerHtml]="domSanitizer.bypassSecurityTrustHtml(feature.description[0])"></span>
                    <div *ngIf="feature.details">
                        <br /><span [innerHtml]="domSanitizer.bypassSecurityTrustHtml(feature.details)"></span>
                    </div>
                </div>
            </div>
        </div>
        <!-- subclasses -->
		<div *ngIf="playerClass.subclasses && playerClass.subclasses.length > 0">
			<br />
			<b>Choose {{playerClass.subclasses[0].subclass_flavor}}</b>:
			<div class="subclass-group">
				<div *ngFor="let subclass of playerClass.subclasses" class="btn-group">
					<button type="button" [class.active]="shownSubclass==subclass.index"
						class="btn btn-outline-primary btn-subclass"
						(click)="showSubclass(subclass.index)">{{subclass.name}}</button>
				</div>
			</div>
			<div *ngFor="let subclass of playerClass.subclasses" [id]="subclass.index">
				<div *ngIf="shownSubclass==subclass.index" class="subtext removeExtraLine">
					<strong>{{subclass.subclass_flavor}} - {{subclass.name}}</strong> - {{subclass.desc}}<br />
					<div class="subtext">
						<div *ngIf="subclass.spells" class="margin-bottom-small">
							<b>Spells:</b>
							<div [innerHtml]="getSpells(subclass.spells)" class="spell-list">
							</div>
						</div>
						<!-- Features that are not level specific -->
						<div *ngFor="let feature of subclass.features">
							<div class="feature">
								<b>{{feature.name}}:</b>&nbsp;
								<div *ngFor="let desc of feature.desc" class="margin-bottom-small">
									{{desc}}
								</div>
							</div>
							<div *ngIf="feature.prerequisites.length > 0">
								<b>Prerequisites:</b>&nbsp;{{getPrerequisites(feature)}}<br />
							</div>
						</div>
                        <!-- Subclass Features by Level -->
                        <div *ngFor="let feature of subclassFeatures" class="removeExtraLine">
                            <div class="feature">
                                <b>{{feature.name}}</b>:&nbsp;
                                <span [innerHtml]="domSanitizer.bypassSecurityTrustHtml(feature.description[0])"></span>
                                <div *ngIf="feature.details">
                                    <br /><span [innerHtml]="domSanitizer.bypassSecurityTrustHtml(feature.details)"></span>
                                </div>
                            </div>
                        </div>
					</div>
				</div>
			</div>
		</div>
        <br/>
		<div *ngIf="playerClass.page">{{playerClass.book}} (page {{playerClass.page}})</div>
	</div>
</div>

// src/components/rules/player-classes/PlayerClass.jsx
import { useState, useEffect } from 'react';
import PlayerClassHeader from './PlayerClassHeader';
import PlayerClassBasicInfo from './PlayerClassBasicInfo';
import PlayerClassFeatures from './PlayerClassFeatures';
import PlayerClassLevels from './PlayerClassLevels';
import PlayerClassSubclasses from './PlayerClassSubclasses';

function PlayerClass({ playerClass, expand, onExpand }) {
    const [isExpanded, setIsExpanded] = useState(expand);
    const [shownLevel, setShownLevel] = useState(0);
    const [shownSubclass, setShownSubclass] = useState('');

    // Update local state when prop changes
    useEffect(() => {
        if (expand !== isExpanded) {
            setIsExpanded(expand);
        }
    }, [expand]);

    const getNameString = (names) => {
        if (!names || names.length === 0) return '';
        let nameString = '';
        names.forEach((name) => {
            nameString += `${name}, `;
        });
        return nameString.substring(0, nameString.length - 2);
    };

    const getPrerequisites = (prerequisites) => {
        if (!prerequisites || prerequisites.length === 0) return '';
        let prerequisitesText = '';
        prerequisites.forEach((prerequisite) => {
            switch (prerequisite.type) {
                case 'feature':
                    prerequisitesText += `feature ${prerequisite.feature.substr(14)}, `;
                    break;
                case 'level':
                    break;
                case 'proficiency':
                    prerequisitesText += `proficiency ${prerequisite.proficiency.substr(19)}, `;
                    break;
                case 'Spell':
                    prerequisitesText += `spell ${prerequisite.spell.substr(12)}, `;
                    break;
                default:
                    prerequisitesText += `${prerequisite.type} ${prerequisite[Object.keys(prerequisite).find(key => key !== 'type')]} , `;
            }
        });
        return prerequisitesText.substring(0, prerequisitesText.length - 2);
    };

    const getSpells = (spells) => {
        if (!spells || spells.length === 0) return '';
        let spellNames = '';
        let lastFeature = '';
        let lastLevel = '';
        spells.forEach((spell) => {
            let level = spell.prerequisites[0].index;
            const levelIndex = level.indexOf('-');
            level = level.substring(levelIndex + 1, 2);
            let feature = '';
            if (spell.prerequisites[1]) {
                feature = spell.prerequisites[1].name;
                if (feature !== lastFeature) {
                    if (lastFeature !== '') {
                        spellNames += `<br/><br/>`;
                    }
                    spellNames += `<b>${feature}</b>:<br/>`;
                }
            }
            if (level !== lastLevel) {
                if (lastLevel !== '' && feature === lastFeature) {
                    spellNames += `<br/>`;
                }
                spellNames += `Level ${level}: ${spell.spell.name}`;
            } else {
                spellNames += `, ${spell.spell.name}`;
            }
            lastFeature = feature;
            lastLevel = level;
        });
        return spellNames;
    };

    const updateFeatures = () => {
        if (!playerClass.class_levels) return [];
        
        const classLevels = playerClass.class_levels.filter((classLevel) => classLevel.level <= shownLevel);
        // Go through levels highest to lowest so is an ability increases at higher levels, that is the one retained in the array
        let classFeatures = [];
        for (let i = classLevels.length - 1; i >= 0; i--) {
            if (classLevels[i].features) {
                classLevels[i].features.forEach((feature) => {
                    const featureSummary = {
                        name: feature.name,
                        description: feature.desc,
                        details: feature.details
                    };
                    if (!classFeatures.some((classFeature) => classFeature.name === feature.name)) {
                        classFeatures.push(featureSummary);
                    }
                });
            }
        }
        return classFeatures;
    };

    const updateSubclassFeatures = () => {
        if (!shownSubclass || !playerClass.subclasses) return [];
        
        const subclass = playerClass.subclasses.find((clonedSubclass) => clonedSubclass.index === shownSubclass);
        if (!subclass || !subclass.class_levels) return [];

        const subclassLevels = subclass.class_levels.filter((classLevel) => classLevel.level <= shownLevel);
        let subclassFeatures = [];
        for (let i = subclassLevels.length - 1; i >= 0; i--) {
            if (subclassLevels[i].features) {
                subclassLevels[i].features.forEach((feature) => {
                    const featureSummary = {
                        name: feature.name,
                        description: feature.desc,
                        details: feature.details
                    };
                    if (!subclassFeatures.some((subclassFeature) => subclassFeature.name === feature.name)) {
                        subclassFeatures.push(featureSummary);
                    }
                });
            }
        }
        return subclassFeatures;
    };

    const toggleDetails = () => {
        setIsExpanded(!isExpanded);
        onExpand(!isExpanded);
    };

    const showLevel = (level) => {
        if (level === shownLevel) {
            setShownLevel(0);
        } else {
            setShownLevel(level);
        }
    };

    const showSubclass = (subclassIndex) => {
        if (subclassIndex === shownSubclass) {
            setShownSubclass('');
        } else {
            setShownSubclass(subclassIndex);
        }
    };

    const classFeatures = updateFeatures();
    const subclassFeatures = updateSubclassFeatures();

    if (!playerClass) {
        return null;
    }

    return (
        <div className={`card outer w-100 ${isExpanded ? 'active' : ''}`} id={playerClass.index}>
            <PlayerClassHeader 
                playerClass={playerClass}
                isExpanded={isExpanded}
                onToggle={toggleDetails}
            />

            {isExpanded && (
                <>
                    <PlayerClassBasicInfo playerClass={playerClass} getNameString={getNameString} />

                    {/* Features that are not level specific */}
                    {playerClass.features && playerClass.features.length > 0 && (
                        <div className="card-body">
                            <PlayerClassFeatures 
                                features={playerClass.features}
                                shownLevel={shownLevel}
                                getPrerequisites={getPrerequisites}
                            />
                        </div>
                    )}

                    <div className="card-body">
                        <PlayerClassLevels 
                            playerClass={playerClass}
                            shownLevel={shownLevel}
                            onShowLevel={showLevel}
                        />
                    </div>

                    <div className="card-body">
                        <PlayerClassSubclasses 
                            playerClass={playerClass}
                            shownLevel={shownLevel}
                            shownSubclass={shownSubclass}
                            onShowSubclass={showSubclass}
                            getSpells={getSpells}
                            classFeatures={classFeatures}
                            subclassFeatures={subclassFeatures}
                        />
                    </div>

                    <div className="card-body">
                        <br />
                        {playerClass.page && (
                            <div>{playerClass.book} (page {playerClass.page})</div>
                        )}
                    </div>
                </>
            )}
        </div>
    );
}

export default PlayerClass;
