// src/app/components/equipment-items/equipment-items.component.ts
﻿import { Component, OnDestroy, OnInit } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { combineLatest, Subscription } from 'rxjs';

import { DataService } from '../../services/data.service';
declare const utils: any // Javascript utilities

@Component({
    selector: 'equipment-items',
    styleUrls: ['./equipment-items.component.css'],
    templateUrl: './equipment-items.component.html',
    standalone: false
})
export class EquipmentItemsComponent implements OnInit, OnDestroy {
    equipmentItems: any[] = [];
    filter = {
        category: 'All',
        bookmarked: 'All',
        name: '',
        property: 'All',
        range: 'All'
    }
    shownCard = '';
    subscriptions: Subscription[] = [];
    weaponProperties: any[] = [];

    constructor(private route: ActivatedRoute, private router: Router, public dataService: DataService) { }

    ngOnInit(): void {
        this.subscriptions.push(combineLatest([
            this.dataService.getEquipment(),
            this.dataService.getWeaponProperties()
        ]).subscribe((data: any) => {
            this.equipmentItems = data[0];
            console.log(`${this.equipmentItems.length} equipment items`);
            this.weaponProperties = data[1];
            const index = this.route.snapshot.queryParamMap.get('index');
            if (index) {
                const equipmentItem = this.equipmentItems.find((equipmentItem) => equipmentItem.index === index);
                if (equipmentItem) {
                    this.expandCard(index, true);
                    utils.scrollIntoView(equipmentItem.index);
                }
            } else {
                // Set search filters
                let filter = localStorage.getItem('equipmentItemsFilter');
                if (filter) {
                    this.filter = JSON.parse(filter);
                } else {
                    localStorage.setItem('equipmentItemsFilter', JSON.stringify(this.filter));
                }
            }
            // Set bookmarked equipment
            let equipmentItemsBookmarkedJson = localStorage.getItem('equipmentItemsBookmarked');
            let equipmentItemsBookmarked: string[] = [];
            if (equipmentItemsBookmarkedJson != null) {
                equipmentItemsBookmarked = JSON.parse(equipmentItemsBookmarkedJson);
            }
            this.equipmentItems.forEach(equipmentItems => {
                equipmentItems.bookmarked = equipmentItemsBookmarked.includes(equipmentItems.index);
            })
        }));
    }

    ngOnDestroy(): void {
        // Unsubscribe all subscriptions to avoid memory leak
        this.subscriptions.forEach(subscription => subscription.unsubscribe());
    }

    expandCard(index: string, expanded: boolean) {
        if (expanded) {
            this.shownCard = index;
            utils.scrollIntoView(index);
        }
        this.router.navigate([], {
            queryParams: { index: index },
            queryParamsHandling: 'merge',
        });
    }

    getWeaponPropertyDescription(name: string) {
        return this.weaponProperties.find(wp => wp.name == name).desc;
    }

    filterChanged(): void {
        localStorage.setItem('equipmentItemsFilter', JSON.stringify(this.filter));
        //console.log(this.equipmentItems);
    }

    saveBookmark(event?: any) {
        let equipmentItemsBookmarked: string[] = [];
        this.equipmentItems.forEach(equipmentItem => {
            if (equipmentItem.bookmarked == true) {
                equipmentItemsBookmarked.push(equipmentItem.index);
            }
        })
        localStorage.setItem('equipmentItemsBookmarked', JSON.stringify(equipmentItemsBookmarked));
    }

    showEquipmentItem(equipmentItem: any) {
        // Bookmarked filter
        if (this.filter.bookmarked != 'All' && !equipmentItem.bookmarked) {
            return false;
        }
        // Category filter
        if (this.filter.category != 'All' && equipmentItem.equipment_category != this.filter.category) {
            return false;
        }
        // Property filter
        // @ts-ignore
        if (this.filter.category == 'Weapon' && this.filter.property != 'All' && !equipmentItem.properties.some(p => p == this.filter.property)) {
            return false;
        }
        // Name filter
        if (this.filter.name != '' && !equipmentItem.name.toLowerCase().includes(this.filter.name.toLowerCase())) {
            return false;
        }
        // Range filter
        if (this.filter.category == 'Weapon' && this.filter.range != 'All' && equipmentItem.weapon_range != this.filter.range) {
            return false;
        }
        return true;
    }

}


﻿<form #searchForm="ngForm" novalidate>
  <!--Name-->
  <label for="name" class="col-form-label">Name</label>
  <div [class.has-error]="nameControl.invalid && nameControl.dirty">
    <input type="text" class="form-control" id="name" name="name" [(ngModel)]="filter.name" #nameControl="ngModel" (ngModelChange)="filterChanged()" pattern="[A-Za-z ]+" maxlength="50">
    <div [hidden]="nameControl.valid || nameControl.pristine" class="alert alert-danger">
      Name should be less than 50 characters
    </div>
  </div>
  <!--Category-->
  <label for="category" class="col-form-label">Category</label>
  <select name="category" [(ngModel)]="filter.category" #categoryControl="ngModel" class="form-control" (ngModelChange)="filterChanged()">
    <option selected>All</option>
    <option>Adventuring Gear</option>
    <option>Armor</option>
    <option>Mounts and Vehicles</option>
    <option>Property</option>
    <option>Tools</option>
    <option>Weapon</option>
  </select>
  <!--Range-->
  @if (filter.category == 'Weapon') {
    <label for="range" class="col-form-label">Range</label>
  }
  @if (filter.category == 'Weapon') {
    <select name="range" [(ngModel)]="filter.range" #rangeControl="ngModel" class="form-control" (ngModelChange)="filterChanged()">
      <option selected>All</option>
      <option>Melee</option>
      <option>Ranged</option>
    </select>
  }
  <!--Properties-->
  @if (filter.category == 'Weapon') {
    <label for="property" class="col-form-label">Property</label>
  }
  @if (filter.category == 'Weapon') {
    <select name="property" [(ngModel)]="filter.property" #rangeControl="ngModel" class="form-control" (ngModelChange)="filterChanged()">
      <option selected>All</option>
      <option>Ammunition</option>
      <option>Finesse</option>
      <option>Heavy</option>
      <option>Light</option>
      <option>Loading</option>
      <option>Monk</option>
      <option>Reach</option>
      <option>Thrown</option>
      <option>Two-Handed</option>
      <option>Versatile</option>
    </select>
  }
  <!--Bookmarked-->
  <label for="bookmarked" class="col-form-label">Bookmarked</label>
  <select name="bookmarked" [(ngModel)]="filter.bookmarked" #bookmarkedControl="ngModel" class="form-control" (ngModelChange)="filterChanged()">
    <option selected>All</option>
    <option>Bookmarked</option>
  </select>
</form>
@if (filter.category == 'Weapon' && filter.property != 'All') {
  <div class="weapon-property-description">
    <b>Weapon Property - {{filter.property}}</b><br />
    {{getWeaponPropertyDescription(filter.property)}}
  </div>
}
@for (equipmentItem of equipmentItems; track equipmentItem) {
  <div class="list" [id]="equipmentItem.index">
    @if (showEquipmentItem(equipmentItem)) {
      <equipment-item-js [equipmentItem]="equipmentItem" [attr.expand]="shownCard==equipmentItem.index" (bookmarkChanged)="saveBookmark($event)" (expanded)="expandCard(equipmentItem.index, $any($event).detail.expanded)"></equipment-item-js>
    }
  </div>
}

// src/components/equipment-items/EquipmentItems.jsx
import { useState, useEffect } from 'react';
import { useLocation, useSearchParams } from 'react-router-dom';
import { useEquipment, useWeaponProperties } from '../../data/dataService';
import { scrollIntoView } from '../../data/utils';
import EquipmentItem from './EquipmentItem';
import EquipmentFilterForm from './EquipmentFilterForm';
import WeaponPropertyDescription from './WeaponPropertyDescription';
import EquipmentItemList from './EquipmentItemList';
import './EquipmentItems.css';

function EquipmentItems() {
    const [equipmentItems, setEquipmentItems] = useState([]);
    const [weaponProperties, setWeaponProperties] = useState([]);
    const [filter, setFilter] = useState({
        category: 'All',
        bookmarked: 'All',
        name: '',
        property: 'All',
        range: 'All'
    });
    const [shownCard, setShownCard] = useState('');
    const location = useLocation();
    const [searchParams, setSearchParams] = useSearchParams();

    // Fetch data
    const { data: equipmentData, loading: equipmentLoading } = useEquipment();
    const { data: weaponPropertiesData, loading: wpLoading } = useWeaponProperties();

    useEffect(() => {
        if (equipmentData && equipmentData.length > 0) {
            setEquipmentItems(equipmentData);
            console.log(`${equipmentData.length} equipment items`);

            // Check for index parameter in URL
            const index = searchParams.get('index');
            if (index) {
                const equipmentItem = equipmentData.find(item => item.index === index);
                if (equipmentItem) {
                    setShownCard(index);
                    scrollIntoView(index);
                }
            } else {
                // Set search filters from localStorage
                const savedFilter = localStorage.getItem('equipmentItemsFilter');
                if (savedFilter) {
                    setFilter(JSON.parse(savedFilter));
                } else {
                    localStorage.setItem('equipmentItemsFilter', JSON.stringify(filter));
                }
            }

            // Set bookmarked status from localStorage
            const equipmentItemsBookmarkedJson = localStorage.getItem('equipmentItemsBookmarked');
            let equipmentItemsBookmarked = [];
            if (equipmentItemsBookmarkedJson) {
                equipmentItemsBookmarked = JSON.parse(equipmentItemsBookmarkedJson);
            }

            // Update bookmarked status for each item
            const updatedItems = equipmentData.map(item => ({
                ...item,
                bookmarked: equipmentItemsBookmarked.includes(item.index)
            }));
            setEquipmentItems(updatedItems);
        }

        if (weaponPropertiesData) {
            setWeaponProperties(weaponPropertiesData);
        }
    }, [equipmentData, weaponPropertiesData]);

    const expandCard = (index, expanded) => {
        if (expanded) {
            setShownCard(index);
            scrollIntoView(index);
        } else {
            setShownCard('');
        }

        // Update URL query params using setSearchParams
        if (expanded) {
            setSearchParams({ index });
        } else {
            setSearchParams({});
        }
    };

    const getWeaponPropertyDescription = (name) => {
        const wp = weaponProperties.find(wp => wp.name === name);
        return wp ? wp.desc : '';
    };

    const filterChanged = (newFilter) => {
        localStorage.setItem('equipmentItemsFilter', JSON.stringify(newFilter));
    };

    const saveBookmark = () => {
        const equipmentItemsBookmarked = equipmentItems
            .filter(item => item.bookmarked)
            .map(item => item.index);
        localStorage.setItem('equipmentItemsBookmarked', JSON.stringify(equipmentItemsBookmarked));
    };

    const showEquipmentItem = (equipmentItem) => {
        // Bookmarked filter
        if (filter.bookmarked !== 'All' && !equipmentItem.bookmarked) {
            return false;
        }
        // Category filter
        if (filter.category !== 'All' && equipmentItem.equipment_category !== filter.category) {
            return false;
        }
        // Property filter (for weapons only)
        if (filter.category === 'Weapon' && filter.property !== 'All') {
            const hasProperty = equipmentItem.properties?.some(p => p === filter.property);
            if (!hasProperty) {
                return false;
            }
        }
        // Name filter
        if (filter.name !== '' && !equipmentItem.name.toLowerCase().includes(filter.name.toLowerCase())) {
            return false;
        }
        // Range filter (for weapons only)
        if (filter.category === 'Weapon' && filter.range !== 'All') {
            // Handle both "Melee" and "Meele" (typo in data)
            const weaponRange = equipmentItem.weapon_range?.toLowerCase().replace('meele', 'melee');
            if (weaponRange !== filter.range.toLowerCase()) {
                return false;
            }
        }
        return true;
    };

    const handleBookmarkChange = (index, isBookmarked) => {
        // Update local state immediately so UI reflects the change
        setEquipmentItems(prevItems => 
            prevItems.map(item => 
                item.index === index ? { ...item, bookmarked: isBookmarked } : item
            )
        );
        
        // Save to localStorage - get current bookmarked items from state
        const equipmentItemsBookmarked = equipmentItems
            .filter(item => item.bookmarked)
            .map(item => item.index);
        
        if (isBookmarked) {
            // Add to bookmarked list
            equipmentItemsBookmarked.push(index);
        } else {
            // Remove from bookmarked list
            const filtered = equipmentItemsBookmarked.filter(i => i !== index);
            localStorage.setItem('equipmentItemsBookmarked', JSON.stringify(filtered));
        }
        
        if (isBookmarked) {
            localStorage.setItem('equipmentItemsBookmarked', JSON.stringify(equipmentItemsBookmarked));
        }
    };

    if (equipmentLoading || wpLoading) {
        return <div className="list"><div>Loading equipment...</div></div>;
    }

    const filteredItems = equipmentItems.filter(showEquipmentItem);

    return (
        <>
            <EquipmentFilterForm 
                filter={filter}
                setFilter={setFilter}
                onFilterChange={filterChanged}
            />

            <WeaponPropertyDescription 
                category={filter.category}
                property={filter.property}
                getWeaponPropertyDescription={getWeaponPropertyDescription}
            />

            <EquipmentItemList 
                filteredItems={filteredItems}
                showEquipmentItem={showEquipmentItem}
                shownCard={shownCard}
                expandCard={expandCard}
                handleBookmarkChange={handleBookmarkChange}
            />
        </>
    );
}

export default EquipmentItems;
