// src/app/components/rules/ability-score/ability-score.component.ts
﻿import { Component, Input, Output, EventEmitter } from '@angular/core';
@Component({
  selector: 'ability-score',
  styleUrls: ['./ability-score.component.scss'],
  templateUrl: './ability-score.component.html'
})
export class AbilityScoreComponent {

  @Input() abilityScore: any = null;
  @Input() expand = false;
  @Output() expanded = new EventEmitter<boolean>();

  getSkills() {
    let skills = '';
    this.abilityScore.skills.forEach((skill: string) => {
      skills += `${skill}, `;
    });
    return skills.substr(0, skills.length - 2);
  }

  toggleDetails() {
    this.expand = !this.expand;
    this.expanded.emit(this.expand);
  }

}

﻿<div *ngIf="abilityScore != null" class="card w-100">
	<div class="card-header clickable" (click)="toggleDetails()">
		<span class="card-title">{{abilityScore.full_name}}</span><span *ngIf="getSkills() != ''" class="align-center">&nbsp;- {{getSkills()}}</span>
	</div>
	<div *ngIf="expand" class="card-body">
		<div class="card-text">
			<div class="removeExtraLine">
				<span *ngFor="let desc of abilityScore.desc">
					{{desc}}<br /><br />
				</span>
			</div>
		</div>
	</div>
</div>

// src/components/rules/AbilityScore.jsx
import { useState } from 'react';

function AbilityScore({ abilityScore, expand, onExpand }) {
    const [isExpanded, setIsExpanded] = useState(expand);

    // Update local state when prop changes
    if (expand !== isExpanded) {
        setIsExpanded(expand);
    }

    const getSkills = () => {
        if (!abilityScore.skills || abilityScore.skills.length === 0) {
            return '';
        }
        const skills = abilityScore.skills.join(', ');
        return skills;
    };

    const toggleDetails = () => {
        setIsExpanded(!isExpanded);
        onExpand(!isExpanded);
    };

    if (!abilityScore) {
        return null;
    }

    const skills = getSkills();

    return (
        <div className={`card w-100 ${isExpanded ? 'active' : ''}`}>
            <div className="card-header clickable" onClick={toggleDetails}>
                <span className="card-title">
                    {abilityScore.full_name}
                </span>
                {skills && (
                    <span className="align-center">
                        &nbsp;- {skills}
                    </span>
                )}
            </div>
            {isExpanded && (
                <div className="card-body">
                    <div 
                        className="card-text"
                        dangerouslySetInnerHTML={{ __html: abilityScore.desc }}
                    />
                </div>
            )}
        </div>
    );
}

export default AbilityScore;
