// src/app/components/rules/ability-scores/ability-scores.component.ts
﻿import { Component, OnDestroy, OnInit } from '@angular/core';
import { combineLatest, Subscription } from 'rxjs';

import { DataService } from '../../../services/data.service';
declare const utils: any // Javascript utilities

@Component({
    selector: 'ability-scores',
    styleUrls: ['./ability-scores.component.css'],
    templateUrl: './ability-scores.component.html',
    standalone: false
})
export class AbilityScoresComponent implements OnInit, OnDestroy {
  abilityScores: any[] = [];
  shownCard = '';
  subscriptions: Subscription[] = [];

  constructor(public dataService: DataService) { }

  ngOnInit(): void {
    this.subscriptions.push(combineLatest([
      this.dataService.getAbilityScores()
    ]).subscribe((data: any) => {
      this.abilityScores = data[0];
    }));
  }

  ngOnDestroy(): void {
    // Unsubscribe all subscriptions to avoid memory leak
    this.subscriptions.forEach(subscription => subscription.unsubscribe());
  }

  expandCard(index: string, expanded: boolean) {
    if(expanded) {
      this.shownCard=index;
      utils.scrollIntoView(index);
    }
  }

}

﻿@for (abilityScore of abilityScores; track abilityScore) {
  <div class="list" [id]="abilityScore.index">
    <ability-score [abilityScore]="abilityScore" [expand]="shownCard==abilityScore.index"
    (expanded)="expandCard(abilityScore.index, $event)"></ability-score>
  </div>
}

// src/components/rules/AbilityScores.jsx
import { useState, useEffect } from 'react';
import { useAbilityScores } from '../../data/dataService';
import AbilityScore from './AbilityScore';
import './AbilityScores.css';

// Javascript utilities (matching Angular)
const utils = {
    scrollIntoView: function(index) {
        const element = document.getElementById(index);
        if (element) {
            element.scrollIntoView({ behavior: 'smooth', block: 'center' });
        }
    }
};

function AbilityScores() {
    const [abilityScores, setAbilityScores] = useState([]);
    const [shownCard, setShownCard] = useState('');

    // Fetch data
    const { data: abilityScoresData, loading } = useAbilityScores();

    useEffect(() => {
        if (abilityScoresData && abilityScoresData.length > 0) {
            setAbilityScores(abilityScoresData);
        }
    }, [abilityScoresData]);

    const expandCard = (index, expanded) => {
        if (expanded) {
            setShownCard(index);
            utils.scrollIntoView(index);
        } else {
            setShownCard('');
        }
    };

    if (loading) {
        return <div className="list"><div>Loading ability scores...</div></div>;
    }

    return (
        <div className="list">
            {abilityScores.map((abilityScore) => (
                <div key={abilityScore.index} id={abilityScore.index}>
                    <AbilityScore 
                        abilityScore={abilityScore}
                        expand={shownCard === abilityScore.index}
                        onExpand={(expanded) => expandCard(abilityScore.index, expanded)}
                    />
                </div>
            ))}
        </div>
    );
}

export default AbilityScores;
